<?php

//require_once( 'modules/ACLRoles/ACLRole.php' );
//require_once( 'custom/modules/Cases/classes/NEPSRolManager.php' );
require_once 'modules/Administration/QuickRepairAndRebuild.php';

class Veta_RequerimientoViewList extends ViewList
{

    public function preDisplay()
    {
        echo '<script type="text/javascript" src="modules/Veta_Requerimiento/javascript/eticcolistview.js"></script>';
        parent::preDisplay(); // TODO: Change the autogenerated stub

        $this->lv->actionsMenuExtraItems[] = $this->getNewActionMenuItem1();
    }


    /**
     * Este metodo crea la accion para exportar los registros en formato csv
     *
     * @return string
     */
    private function getNewActionMenuItem1()
    {
        return <<<EOF
        <a href='javascript:void(0)' target="_blank" 
        onclick="return enviar_form()">Crear lista de público objetivo</a>
EOF;
    }

}