<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2017 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */



// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '6.5.25',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => '',
  'author' => '',
  'description' => 'LLamadas, Tareas , Reuniones y Notas',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Actividades',
  'published_date' => '2019-10-10 17:39:23',
  'type' => 'module',
  'version' => 1570729165,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'Actividades',
  'relationships' => 
  array (
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/include/language/es_ES.Actividades.php',
      'to_module' => 'application',
      'language' => 'es_ES',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/include/language/en_us.Actividades.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Calls/language/en_us.lang.php',
      'to_module' => 'Calls',
      'language' => 'en_us',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Calls/language/es_ES.lang.php',
      'to_module' => 'Calls',
      'language' => 'es_ES',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Meetings/language/en_us.lang.php',
      'to_module' => 'Meetings',
      'language' => 'en_us',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Meetings/language/es_ES.lang.php',
      'to_module' => 'Meetings',
      'language' => 'es_ES',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Notes/language/en_us.lang.php',
      'to_module' => 'Notes',
      'language' => 'en_us',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Notes/language/es_ES.lang.php',
      'to_module' => 'Notes',
      'language' => 'es_ES',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Tasks/language/en_us.lang.php',
      'to_module' => 'Tasks',
      'language' => 'en_us',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Tasks/language/es_ES.lang.php',
      'to_module' => 'Tasks',
      'language' => 'es_ES',
    ),
  ),
  'custom_fields' => 
  array (
    'Callscontact_id_c' => 
    array (
      'id' => 'Callscontact_id_c',
      'name' => 'contact_id_c',
      'label' => 'LBL_ESTUDIANTE_CONTACT_ID',
      'comments' => '',
      'help' => '',
      'module' => 'Calls',
      'type' => 'id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2018-07-13 20:39:31',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Callsestudiante_c' => 
    array (
      'id' => 'Callsestudiante_c',
      'name' => 'estudiante_c',
      'label' => 'LBL_ESTUDIANTE',
      'comments' => '',
      'help' => '',
      'module' => 'Calls',
      'type' => 'relate',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2018-07-13 20:39:31',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => 'Contacts',
      'ext3' => 'contact_id_c',
      'ext4' => '',
    ),
    'Meetingscontact_id_c' => 
    array (
      'id' => 'Meetingscontact_id_c',
      'name' => 'contact_id_c',
      'label' => 'LBL_ESTUDIANTE_CONTACT_ID',
      'comments' => '',
      'help' => '',
      'module' => 'Meetings',
      'type' => 'id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2018-07-13 21:59:03',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Meetingsestudiante_c' => 
    array (
      'id' => 'Meetingsestudiante_c',
      'name' => 'estudiante_c',
      'label' => 'LBL_ESTUDIANTE',
      'comments' => '',
      'help' => '',
      'module' => 'Meetings',
      'type' => 'relate',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2018-07-13 21:59:03',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => 'Contacts',
      'ext3' => 'contact_id_c',
      'ext4' => '',
    ),
    'Meetingsjjwg_maps_address_c' => 
    array (
      'id' => 'Meetingsjjwg_maps_address_c',
      'name' => 'jjwg_maps_address_c',
      'label' => 'LBL_JJWG_MAPS_ADDRESS',
      'comments' => 'Address',
      'help' => 'Address',
      'module' => 'Meetings',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2018-02-16 18:47:21',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Meetingsjjwg_maps_geocode_status_c' => 
    array (
      'id' => 'Meetingsjjwg_maps_geocode_status_c',
      'name' => 'jjwg_maps_geocode_status_c',
      'label' => 'LBL_JJWG_MAPS_GEOCODE_STATUS',
      'comments' => 'Geocode Status',
      'help' => 'Geocode Status',
      'module' => 'Meetings',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2018-02-16 18:47:21',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Meetingsjjwg_maps_lat_c' => 
    array (
      'id' => 'Meetingsjjwg_maps_lat_c',
      'name' => 'jjwg_maps_lat_c',
      'label' => 'LBL_JJWG_MAPS_LAT',
      'comments' => '',
      'help' => 'Latitude',
      'module' => 'Meetings',
      'type' => 'float',
      'max_size' => '10',
      'require_option' => '0',
      'default_value' => '0.00000000',
      'date_modified' => '2018-02-16 18:47:21',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '8',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Meetingsjjwg_maps_lng_c' => 
    array (
      'id' => 'Meetingsjjwg_maps_lng_c',
      'name' => 'jjwg_maps_lng_c',
      'label' => 'LBL_JJWG_MAPS_LNG',
      'comments' => '',
      'help' => 'Longitude',
      'module' => 'Meetings',
      'type' => 'float',
      'max_size' => '11',
      'require_option' => '0',
      'default_value' => '0.00000000',
      'date_modified' => '2018-02-16 18:47:21',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '8',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Notescontact_id_c' => 
    array (
      'id' => 'Notescontact_id_c',
      'name' => 'contact_id_c',
      'label' => 'LBL_ESTUDIANTE_CONTACT_ID',
      'comments' => '',
      'help' => '',
      'module' => 'Notes',
      'type' => 'id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2018-07-15 17:10:01',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Notesestudiante_c' => 
    array (
      'id' => 'Notesestudiante_c',
      'name' => 'estudiante_c',
      'label' => 'LBL_ESTUDIANTE',
      'comments' => '',
      'help' => '',
      'module' => 'Notes',
      'type' => 'relate',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2018-07-15 17:10:01',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => 'Contacts',
      'ext3' => 'contact_id_c',
      'ext4' => '',
    ),
    'Taskscontact_id_c' => 
    array (
      'id' => 'Taskscontact_id_c',
      'name' => 'contact_id_c',
      'label' => 'LBL_ESTUDIANTE_CONTACT_ID',
      'comments' => '',
      'help' => '',
      'module' => 'Tasks',
      'type' => 'id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2018-07-13 20:44:45',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Tasksestudiante_c' => 
    array (
      'id' => 'Tasksestudiante_c',
      'name' => 'estudiante_c',
      'label' => 'LBL_ESTUDIANTE',
      'comments' => '',
      'help' => '',
      'module' => 'Tasks',
      'type' => 'relate',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2018-07-13 20:44:45',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => 'Contacts',
      'ext3' => 'contact_id_c',
      'ext4' => '',
    ),
  ),
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Calls/metadata/SearchFields.php',
      'to' => 'custom/modules/Calls/metadata/SearchFields.php',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Calls/metadata/SearchFields.php',
      'to' => 'custom/working/modules/Calls/metadata/SearchFields.php',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Calls/metadata/detailviewdefs.php',
      'to' => 'custom/modules/Calls/metadata/detailviewdefs.php',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Calls/metadata/detailviewdefs.php',
      'to' => 'custom/working/modules/Calls/metadata/detailviewdefs.php',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Calls/metadata/editviewdefs.php',
      'to' => 'custom/modules/Calls/metadata/editviewdefs.php',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Calls/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/Calls/metadata/editviewdefs.php',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Calls/metadata/listviewdefs.php',
      'to' => 'custom/modules/Calls/metadata/listviewdefs.php',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Calls/metadata/popupdefs.php',
      'to' => 'custom/modules/Calls/metadata/popupdefs.php',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Calls/metadata/popupdefs.php',
      'to' => 'custom/working/modules/Calls/metadata/popupdefs.php',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Calls/metadata/searchdefs.php',
      'to' => 'custom/modules/Calls/metadata/searchdefs.php',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Calls/metadata/searchdefs.php',
      'to' => 'custom/working/modules/Calls/metadata/searchdefs.php',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Meetings/metadata/SearchFields.php',
      'to' => 'custom/modules/Meetings/metadata/SearchFields.php',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Meetings/metadata/SearchFields.php',
      'to' => 'custom/working/modules/Meetings/metadata/SearchFields.php',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Meetings/metadata/detailviewdefs.php',
      'to' => 'custom/modules/Meetings/metadata/detailviewdefs.php',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Meetings/metadata/detailviewdefs.php',
      'to' => 'custom/working/modules/Meetings/metadata/detailviewdefs.php',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Meetings/metadata/editviewdefs.php',
      'to' => 'custom/modules/Meetings/metadata/editviewdefs.php',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Meetings/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/Meetings/metadata/editviewdefs.php',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Meetings/metadata/listviewdefs.php',
      'to' => 'custom/modules/Meetings/metadata/listviewdefs.php',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Meetings/metadata/popupdefs.php',
      'to' => 'custom/modules/Meetings/metadata/popupdefs.php',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Meetings/metadata/popupdefs.php',
      'to' => 'custom/working/modules/Meetings/metadata/popupdefs.php',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Meetings/metadata/searchdefs.php',
      'to' => 'custom/modules/Meetings/metadata/searchdefs.php',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Meetings/metadata/searchdefs.php',
      'to' => 'custom/working/modules/Meetings/metadata/searchdefs.php',
    ),
    22 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Notes/metadata/SearchFields.php',
      'to' => 'custom/modules/Notes/metadata/SearchFields.php',
    ),
    23 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Notes/metadata/SearchFields.php',
      'to' => 'custom/working/modules/Notes/metadata/SearchFields.php',
    ),
    24 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Notes/metadata/detailviewdefs.php',
      'to' => 'custom/modules/Notes/metadata/detailviewdefs.php',
    ),
    25 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Notes/metadata/detailviewdefs.php',
      'to' => 'custom/working/modules/Notes/metadata/detailviewdefs.php',
    ),
    26 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Notes/metadata/editviewdefs.php',
      'to' => 'custom/modules/Notes/metadata/editviewdefs.php',
    ),
    27 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Notes/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/Notes/metadata/editviewdefs.php',
    ),
    28 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Notes/metadata/listviewdefs.php',
      'to' => 'custom/modules/Notes/metadata/listviewdefs.php',
    ),
    29 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Notes/metadata/popupdefs.php',
      'to' => 'custom/modules/Notes/metadata/popupdefs.php',
    ),
    30 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Notes/metadata/popupdefs.php',
      'to' => 'custom/working/modules/Notes/metadata/popupdefs.php',
    ),
    31 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Notes/metadata/quickcreatedefs.php',
      'to' => 'custom/modules/Notes/metadata/quickcreatedefs.php',
    ),
    32 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Notes/metadata/quickcreatedefs.php',
      'to' => 'custom/working/modules/Notes/metadata/quickcreatedefs.php',
    ),
    33 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Notes/metadata/searchdefs.php',
      'to' => 'custom/modules/Notes/metadata/searchdefs.php',
    ),
    34 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Notes/metadata/searchdefs.php',
      'to' => 'custom/working/modules/Notes/metadata/searchdefs.php',
    ),
    35 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Tasks/metadata/SearchFields.php',
      'to' => 'custom/modules/Tasks/metadata/SearchFields.php',
    ),
    36 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Tasks/metadata/SearchFields.php',
      'to' => 'custom/working/modules/Tasks/metadata/SearchFields.php',
    ),
    37 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Tasks/metadata/detailviewdefs.php',
      'to' => 'custom/modules/Tasks/metadata/detailviewdefs.php',
    ),
    38 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Tasks/metadata/detailviewdefs.php',
      'to' => 'custom/working/modules/Tasks/metadata/detailviewdefs.php',
    ),
    39 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Tasks/metadata/editviewdefs.php',
      'to' => 'custom/modules/Tasks/metadata/editviewdefs.php',
    ),
    40 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Tasks/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/Tasks/metadata/editviewdefs.php',
    ),
    41 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Tasks/metadata/listviewdefs.php',
      'to' => 'custom/modules/Tasks/metadata/listviewdefs.php',
    ),
    42 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Tasks/metadata/popupdefs.php',
      'to' => 'custom/modules/Tasks/metadata/popupdefs.php',
    ),
    43 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Tasks/metadata/popupdefs.php',
      'to' => 'custom/working/modules/Tasks/metadata/popupdefs.php',
    ),
    44 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Tasks/metadata/searchdefs.php',
      'to' => 'custom/modules/Tasks/metadata/searchdefs.php',
    ),
    45 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Tasks/metadata/searchdefs.php',
      'to' => 'custom/working/modules/Tasks/metadata/searchdefs.php',
    ),
    46 => 
    array (
      'from' => '<basepath>/Extension/modules/Tasks/Ext/Language/en_us.Veta.php',
      'to' => 'custom/Extension/modules/Tasks/Ext/Language/en_us.Veta.php',
    ),
    47 => 
    array (
      'from' => '<basepath>/Extension/modules/Tasks/Ext/Language/es_ES.Veta.php',
      'to' => 'custom/Extension/modules/Tasks/Ext/Language/es_ES.Veta.php',
    ),
    48 => 
    array (
      'from' => '<basepath>/Extension/modules/Tasks/Ext/Vardefs/sugarfield_contact_id_c.php',
      'to' => 'custom/Extension/modules/Tasks/Ext/Vardefs/sugarfield_contact_id_c.php',
    ),
    49 => 
    array (
      'from' => '<basepath>/Extension/modules/Tasks/Ext/Vardefs/veta_aplicacion_activities_tasks_Tasks.php',
      'to' => 'custom/Extension/modules/Tasks/Ext/Vardefs/veta_aplicacion_activities_tasks_Tasks.php',
    ),
    50 => 
    array (
      'from' => '<basepath>/Extension/modules/Tasks/Ext/Vardefs/veta_liquidacion_activities_tasks_Tasks.php',
      'to' => 'custom/Extension/modules/Tasks/Ext/Vardefs/veta_liquidacion_activities_tasks_Tasks.php',
    ),
    51 => 
    array (
      'from' => '<basepath>/Extension/modules/Tasks/Ext/Vardefs/veta_loo_activities_tasks_Tasks.php',
      'to' => 'custom/Extension/modules/Tasks/Ext/Vardefs/veta_loo_activities_tasks_Tasks.php',
    ),
    52 => 
    array (
      'from' => '<basepath>/Extension/modules/Tasks/Ext/Vardefs/sugarfield_estudiante_c.php',
      'to' => 'custom/Extension/modules/Tasks/Ext/Vardefs/sugarfield_estudiante_c.php',
    ),
    53 => 
    array (
      'from' => '<basepath>/Extension/modules/Tasks/Ext/Vardefs/veta_pagocolegios_activities_tasks_Tasks.php',
      'to' => 'custom/Extension/modules/Tasks/Ext/Vardefs/veta_pagocolegios_activities_tasks_Tasks.php',
    ),
    54 => 
    array (
      'from' => '<basepath>/Extension/modules/Tasks/Ext/Vardefs/veta_coe_activities_tasks_Tasks.php',
      'to' => 'custom/Extension/modules/Tasks/Ext/Vardefs/veta_coe_activities_tasks_Tasks.php',
    ),
    55 => 
    array (
      'from' => '<basepath>/Extension/modules/Tasks/Ext/Vardefs/veta_visa_activities_tasks_Tasks.php',
      'to' => 'custom/Extension/modules/Tasks/Ext/Vardefs/veta_visa_activities_tasks_Tasks.php',
    ),
    56 => 
    array (
      'from' => '<basepath>/Extension/modules/Notes/Ext/Language/en_us.Veta.php',
      'to' => 'custom/Extension/modules/Notes/Ext/Language/en_us.Veta.php',
    ),
    57 => 
    array (
      'from' => '<basepath>/Extension/modules/Notes/Ext/Language/es_ES.Veta.php',
      'to' => 'custom/Extension/modules/Notes/Ext/Language/es_ES.Veta.php',
    ),
    58 => 
    array (
      'from' => '<basepath>/Extension/modules/Notes/Ext/Vardefs/sugarfield_contact_id_c.php',
      'to' => 'custom/Extension/modules/Notes/Ext/Vardefs/sugarfield_contact_id_c.php',
    ),
    59 => 
    array (
      'from' => '<basepath>/Extension/modules/Notes/Ext/Vardefs/veta_liquidacion_activities_notes_Notes.php',
      'to' => 'custom/Extension/modules/Notes/Ext/Vardefs/veta_liquidacion_activities_notes_Notes.php',
    ),
    60 => 
    array (
      'from' => '<basepath>/Extension/modules/Notes/Ext/Vardefs/sugarfield_estudiante_c.php',
      'to' => 'custom/Extension/modules/Notes/Ext/Vardefs/sugarfield_estudiante_c.php',
    ),
    61 => 
    array (
      'from' => '<basepath>/Extension/modules/Notes/Ext/Vardefs/veta_loo_activities_notes_Notes.php',
      'to' => 'custom/Extension/modules/Notes/Ext/Vardefs/veta_loo_activities_notes_Notes.php',
    ),
    62 => 
    array (
      'from' => '<basepath>/Extension/modules/Notes/Ext/Vardefs/veta_aplicacion_activities_notes_Notes.php',
      'to' => 'custom/Extension/modules/Notes/Ext/Vardefs/veta_aplicacion_activities_notes_Notes.php',
    ),
    63 => 
    array (
      'from' => '<basepath>/Extension/modules/Notes/Ext/Vardefs/veta_coe_activities_notes_Notes.php',
      'to' => 'custom/Extension/modules/Notes/Ext/Vardefs/veta_coe_activities_notes_Notes.php',
    ),
    64 => 
    array (
      'from' => '<basepath>/Extension/modules/Notes/Ext/Vardefs/veta_pagocolegios_activities_notes_Notes.php',
      'to' => 'custom/Extension/modules/Notes/Ext/Vardefs/veta_pagocolegios_activities_notes_Notes.php',
    ),
    65 => 
    array (
      'from' => '<basepath>/Extension/modules/Notes/Ext/Vardefs/veta_visa_activities_notes_Notes.php',
      'to' => 'custom/Extension/modules/Notes/Ext/Vardefs/veta_visa_activities_notes_Notes.php',
    ),
    66 => 
    array (
      'from' => '<basepath>/Extension/modules/Calls/Ext/Language/en_us.Veta.php',
      'to' => 'custom/Extension/modules/Calls/Ext/Language/en_us.Veta.php',
    ),
    67 => 
    array (
      'from' => '<basepath>/Extension/modules/Calls/Ext/Language/es_ES.Veta.php',
      'to' => 'custom/Extension/modules/Calls/Ext/Language/es_ES.Veta.php',
    ),
    68 => 
    array (
      'from' => '<basepath>/Extension/modules/Calls/Ext/Vardefs/sugarfield_contact_id_c.php',
      'to' => 'custom/Extension/modules/Calls/Ext/Vardefs/sugarfield_contact_id_c.php',
    ),
    69 => 
    array (
      'from' => '<basepath>/Extension/modules/Calls/Ext/Vardefs/veta_liquidacion_activities_calls_Calls.php',
      'to' => 'custom/Extension/modules/Calls/Ext/Vardefs/veta_liquidacion_activities_calls_Calls.php',
    ),
    70 => 
    array (
      'from' => '<basepath>/Extension/modules/Calls/Ext/Vardefs/veta_aplicacion_activities_calls_Calls.php',
      'to' => 'custom/Extension/modules/Calls/Ext/Vardefs/veta_aplicacion_activities_calls_Calls.php',
    ),
    71 => 
    array (
      'from' => '<basepath>/Extension/modules/Calls/Ext/Vardefs/sugarfield_estudiante_c.php',
      'to' => 'custom/Extension/modules/Calls/Ext/Vardefs/sugarfield_estudiante_c.php',
    ),
    72 => 
    array (
      'from' => '<basepath>/Extension/modules/Calls/Ext/Vardefs/veta_coe_activities_calls_Calls.php',
      'to' => 'custom/Extension/modules/Calls/Ext/Vardefs/veta_coe_activities_calls_Calls.php',
    ),
    73 => 
    array (
      'from' => '<basepath>/Extension/modules/Calls/Ext/Vardefs/veta_pagocolegios_activities_calls_Calls.php',
      'to' => 'custom/Extension/modules/Calls/Ext/Vardefs/veta_pagocolegios_activities_calls_Calls.php',
    ),
    74 => 
    array (
      'from' => '<basepath>/Extension/modules/Calls/Ext/Vardefs/veta_visa_activities_calls_Calls.php',
      'to' => 'custom/Extension/modules/Calls/Ext/Vardefs/veta_visa_activities_calls_Calls.php',
    ),
    75 => 
    array (
      'from' => '<basepath>/Extension/modules/Calls/Ext/Vardefs/veta_loo_activities_calls_Calls.php',
      'to' => 'custom/Extension/modules/Calls/Ext/Vardefs/veta_loo_activities_calls_Calls.php',
    ),
    76 => 
    array (
      'from' => '<basepath>/Extension/modules/Meetings/Ext/Language/en_us.Veta.php',
      'to' => 'custom/Extension/modules/Meetings/Ext/Language/en_us.Veta.php',
    ),
    77 => 
    array (
      'from' => '<basepath>/Extension/modules/Meetings/Ext/Language/es_ES.Veta.php',
      'to' => 'custom/Extension/modules/Meetings/Ext/Language/es_ES.Veta.php',
    ),
    78 => 
    array (
      'from' => '<basepath>/Extension/modules/Meetings/Ext/Vardefs/sugarfield_contact_id_c.php',
      'to' => 'custom/Extension/modules/Meetings/Ext/Vardefs/sugarfield_contact_id_c.php',
    ),
    79 => 
    array (
      'from' => '<basepath>/Extension/modules/Meetings/Ext/Vardefs/sugarfield_location.php',
      'to' => 'custom/Extension/modules/Meetings/Ext/Vardefs/sugarfield_location.php',
    ),
    80 => 
    array (
      'from' => '<basepath>/Extension/modules/Meetings/Ext/Vardefs/sugarfield_jjwg_maps_geocode_status_c.php',
      'to' => 'custom/Extension/modules/Meetings/Ext/Vardefs/sugarfield_jjwg_maps_geocode_status_c.php',
    ),
    81 => 
    array (
      'from' => '<basepath>/Extension/modules/Meetings/Ext/Vardefs/sugarfield_date_start.php',
      'to' => 'custom/Extension/modules/Meetings/Ext/Vardefs/sugarfield_date_start.php',
    ),
    82 => 
    array (
      'from' => '<basepath>/Extension/modules/Meetings/Ext/Vardefs/sugarfield_deleted.php',
      'to' => 'custom/Extension/modules/Meetings/Ext/Vardefs/sugarfield_deleted.php',
    ),
    83 => 
    array (
      'from' => '<basepath>/Extension/modules/Meetings/Ext/Vardefs/sugarfield_description.php',
      'to' => 'custom/Extension/modules/Meetings/Ext/Vardefs/sugarfield_description.php',
    ),
    84 => 
    array (
      'from' => '<basepath>/Extension/modules/Meetings/Ext/Vardefs/sugarfield_jjwg_maps_lat_c.php',
      'to' => 'custom/Extension/modules/Meetings/Ext/Vardefs/sugarfield_jjwg_maps_lat_c.php',
    ),
    85 => 
    array (
      'from' => '<basepath>/Extension/modules/Meetings/Ext/Vardefs/veta_coe_activities_meetings_Meetings.php',
      'to' => 'custom/Extension/modules/Meetings/Ext/Vardefs/veta_coe_activities_meetings_Meetings.php',
    ),
    86 => 
    array (
      'from' => '<basepath>/Extension/modules/Meetings/Ext/Vardefs/sugarfield_estudiante_c.php',
      'to' => 'custom/Extension/modules/Meetings/Ext/Vardefs/sugarfield_estudiante_c.php',
    ),
    87 => 
    array (
      'from' => '<basepath>/Extension/modules/Meetings/Ext/Vardefs/sugarfield_parent_type.php',
      'to' => 'custom/Extension/modules/Meetings/Ext/Vardefs/sugarfield_parent_type.php',
    ),
    88 => 
    array (
      'from' => '<basepath>/Extension/modules/Meetings/Ext/Vardefs/veta_pagocolegios_activities_meetings_Meetings.php',
      'to' => 'custom/Extension/modules/Meetings/Ext/Vardefs/veta_pagocolegios_activities_meetings_Meetings.php',
    ),
    89 => 
    array (
      'from' => '<basepath>/Extension/modules/Meetings/Ext/Vardefs/veta_aplicacion_activities_meetings_Meetings.php',
      'to' => 'custom/Extension/modules/Meetings/Ext/Vardefs/veta_aplicacion_activities_meetings_Meetings.php',
    ),
    90 => 
    array (
      'from' => '<basepath>/Extension/modules/Meetings/Ext/Vardefs/sugarfield_name.php',
      'to' => 'custom/Extension/modules/Meetings/Ext/Vardefs/sugarfield_name.php',
    ),
    91 => 
    array (
      'from' => '<basepath>/Extension/modules/Meetings/Ext/Vardefs/veta_liquidacion_activities_meetings_Meetings.php',
      'to' => 'custom/Extension/modules/Meetings/Ext/Vardefs/veta_liquidacion_activities_meetings_Meetings.php',
    ),
    92 => 
    array (
      'from' => '<basepath>/Extension/modules/Meetings/Ext/Vardefs/veta_loo_activities_meetings_Meetings.php',
      'to' => 'custom/Extension/modules/Meetings/Ext/Vardefs/veta_loo_activities_meetings_Meetings.php',
    ),
    93 => 
    array (
      'from' => '<basepath>/Extension/modules/Meetings/Ext/Vardefs/sugarfield_status.php',
      'to' => 'custom/Extension/modules/Meetings/Ext/Vardefs/sugarfield_status.php',
    ),
    94 => 
    array (
      'from' => '<basepath>/Extension/modules/Meetings/Ext/Vardefs/sugarfield_jjwg_maps_lng_c.php',
      'to' => 'custom/Extension/modules/Meetings/Ext/Vardefs/sugarfield_jjwg_maps_lng_c.php',
    ),
    95 => 
    array (
      'from' => '<basepath>/Extension/modules/Meetings/Ext/Vardefs/sugarfield_jjwg_maps_address_c.php',
      'to' => 'custom/Extension/modules/Meetings/Ext/Vardefs/sugarfield_jjwg_maps_address_c.php',
    ),
    96 => 
    array (
      'from' => '<basepath>/Extension/modules/Meetings/Ext/Vardefs/veta_visa_activities_meetings_Meetings.php',
      'to' => 'custom/Extension/modules/Meetings/Ext/Vardefs/veta_visa_activities_meetings_Meetings.php',
    ),
  ),
);