<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2017 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */



// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '6.5.25',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => '',
  'author' => '',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Campañas',
  'published_date' => '2019-10-09 18:45:11',
  'type' => 'module',
  'version' => 1570646711,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'Campañas',
  'relationships' => 
  array (
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/include/language/es_ES.Campañas.php',
      'to_module' => 'application',
      'language' => 'es_ES',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/include/language/en_us.Campañas.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Campaigns/language/en_us.lang.php',
      'to_module' => 'Campaigns',
      'language' => 'en_us',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Campaigns/language/es_ES.lang.php',
      'to_module' => 'Campaigns',
      'language' => 'es_ES',
    ),
  ),
  'custom_fields' => 
  array (
    'Campaignsorigen_c' => 
    array (
      'id' => 'Campaignsorigen_c',
      'name' => 'origen_c',
      'label' => 'LBL_ORIGEN',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'Campaigns',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-06-26 20:52:49',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '1',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'lead_source_dom',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
  ),
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Campaigns/metadata/SearchFields.php',
      'to' => 'custom/modules/Campaigns/metadata/SearchFields.php',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Campaigns/metadata/SearchFields.php',
      'to' => 'custom/working/modules/Campaigns/metadata/SearchFields.php',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Campaigns/metadata/detailviewdefs.php',
      'to' => 'custom/modules/Campaigns/metadata/detailviewdefs.php',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Campaigns/metadata/detailviewdefs.php',
      'to' => 'custom/working/modules/Campaigns/metadata/detailviewdefs.php',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Campaigns/metadata/editviewdefs.php',
      'to' => 'custom/modules/Campaigns/metadata/editviewdefs.php',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Campaigns/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/Campaigns/metadata/editviewdefs.php',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Campaigns/metadata/listviewdefs.php',
      'to' => 'custom/modules/Campaigns/metadata/listviewdefs.php',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Campaigns/metadata/popupdefs.php',
      'to' => 'custom/modules/Campaigns/metadata/popupdefs.php',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Campaigns/metadata/popupdefs.php',
      'to' => 'custom/working/modules/Campaigns/metadata/popupdefs.php',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Campaigns/metadata/searchdefs.php',
      'to' => 'custom/modules/Campaigns/metadata/searchdefs.php',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Campaigns/metadata/searchdefs.php',
      'to' => 'custom/working/modules/Campaigns/metadata/searchdefs.php',
    ),
    11 => 
    array (
      'from' => '<basepath>/Extension/modules/Prospects/Ext/Vardefs/sugarfield_jjwg_maps_geocode_status_c.php',
      'to' => 'custom/Extension/modules/Prospects/Ext/Vardefs/sugarfield_jjwg_maps_geocode_status_c.php',
    ),
    12 => 
    array (
      'from' => '<basepath>/Extension/modules/Prospects/Ext/Vardefs/sugarfield_jjwg_maps_lat_c.php',
      'to' => 'custom/Extension/modules/Prospects/Ext/Vardefs/sugarfield_jjwg_maps_lat_c.php',
    ),
    13 => 
    array (
      'from' => '<basepath>/Extension/modules/Prospects/Ext/Vardefs/sugarfield_jjwg_maps_lng_c.php',
      'to' => 'custom/Extension/modules/Prospects/Ext/Vardefs/sugarfield_jjwg_maps_lng_c.php',
    ),
    14 => 
    array (
      'from' => '<basepath>/Extension/modules/Prospects/Ext/Vardefs/sugarfield_jjwg_maps_address_c.php',
      'to' => 'custom/Extension/modules/Prospects/Ext/Vardefs/sugarfield_jjwg_maps_address_c.php',
    ),
    15 => 
    array (
      'from' => '<basepath>/Extension/modules/Campaigns/Ext/Vardefs/sugarfield_origen_c.php',
      'to' => 'custom/Extension/modules/Campaigns/Ext/Vardefs/sugarfield_origen_c.php',
    ),
  ),
);