<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2017 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */



// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '6.5.25',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => '',
  'author' => '',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Estudiante',
  'published_date' => '2019-10-09 18:58:27',
  'type' => 'module',
  'version' => 1570647509,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'Estudiante',
  'relationships' => 
  array (
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/include/language/en_us.Estudiante.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/include/language/es_ES.Estudiante.php',
      'to_module' => 'application',
      'language' => 'es_ES',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/language/en_us.lang.php',
      'to_module' => 'Contacts',
      'language' => 'en_us',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/language/es_ES.lang.php',
      'to_module' => 'Contacts',
      'language' => 'es_ES',
    ),
  ),
  'custom_fields' => 
  array (
    'Contactsanos_sin_estudiar_c' => 
    array (
      'id' => 'Contactsanos_sin_estudiar_c',
      'name' => 'anos_sin_estudiar_c',
      'label' => 'LBL_ANOS_SIN_ESTUDIAR',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'int',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-02-17 13:31:43',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '0',
      'ext2' => '200',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactscelular_autralia_c' => 
    array (
      'id' => 'Contactscelular_autralia_c',
      'name' => 'celular_autralia_c',
      'label' => 'LBL_CELULAR_AUTRALIA',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-02-17 13:32:25',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactscelular_contacto_emergencia_c' => 
    array (
      'id' => 'Contactscelular_contacto_emergencia_c',
      'name' => 'celular_contacto_emergencia_c',
      'label' => 'LBL_CELULAR_CONTACTO_EMERGENCIA',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-02-17 13:33:02',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsciudad_c' => 
    array (
      'id' => 'Contactsciudad_c',
      'name' => 'ciudad_c',
      'label' => 'LBL_CIUDAD',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'dynamicenum',
      'max_size' => '100',
      'require_option' => '1',
      'default_value' => NULL,
      'date_modified' => '2018-02-17 13:37:00',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'ciudades_list',
      'ext2' => 'departamento_c',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsciudad_nacimiento_c' => 
    array (
      'id' => 'Contactsciudad_nacimiento_c',
      'name' => 'ciudad_nacimiento_c',
      'label' => 'LBL_CIUDAD_NACIMIENTO',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'dynamicenum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2018-02-17 13:40:13',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'ciudades_list',
      'ext2' => 'departamento_nacimiento_c',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactscontacto_emergencia_c' => 
    array (
      'id' => 'Contactscontacto_emergencia_c',
      'name' => 'contacto_emergencia_c',
      'label' => 'LBL_CONTACTO_EMERGENCIA',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-02-17 13:40:42',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactscuenta_bancaria_australia_c' => 
    array (
      'id' => 'Contactscuenta_bancaria_australia_c',
      'name' => 'cuenta_bancaria_australia_c',
      'label' => 'LBL_CUENTA_BANCARIA_AUSTRALIA',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-02-17 13:41:20',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsdepartamento_c' => 
    array (
      'id' => 'Contactsdepartamento_c',
      'name' => 'departamento_c',
      'label' => 'LBL_DEPARTAMENTO',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'dynamicenum',
      'max_size' => '100',
      'require_option' => '1',
      'default_value' => NULL,
      'date_modified' => '2018-02-17 13:35:16',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'departamentos_list',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsdepartamento_nacimiento_c' => 
    array (
      'id' => 'Contactsdepartamento_nacimiento_c',
      'name' => 'departamento_nacimiento_c',
      'label' => 'LBL_DEPARTAMENTO_NACIMIENTO',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'dynamicenum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2018-02-17 13:39:21',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'departamentos_list',
      'ext2' => 'pais_nacimiento_c',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsdireccion_c' => 
    array (
      'id' => 'Contactsdireccion_c',
      'name' => 'direccion_c',
      'label' => 'LBL_DIRECCION',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '1',
      'default_value' => '',
      'date_modified' => '2018-02-17 13:42:10',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsedad_c' => 
    array (
      'id' => 'Contactsedad_c',
      'name' => 'edad_c',
      'label' => 'LBL_EDAD',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'int',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-02-17 13:42:59',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '0',
      'ext2' => '200',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsedad_conyuge_c' => 
    array (
      'id' => 'Contactsedad_conyuge_c',
      'name' => 'edad_conyuge_c',
      'label' => 'LBL_EDAD_CONYUGE',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'int',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-02-17 13:43:49',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '0',
      'ext2' => '200',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsemail_contacto_emergencia_c' => 
    array (
      'id' => 'Contactsemail_contacto_emergencia_c',
      'name' => 'email_contacto_emergencia_c',
      'label' => 'LBL_EMAIL_CONTACTO_EMERGENCIA',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-02-17 13:44:56',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsestado_civil_c' => 
    array (
      'id' => 'Contactsestado_civil_c',
      'name' => 'estado_civil_c',
      'label' => 'LBL_ESTADO_CIVIL',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-02-17 13:45:47',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'estado_civil_list',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsfecha_expiracion_visa_c' => 
    array (
      'id' => 'Contactsfecha_expiracion_visa_c',
      'name' => 'fecha_expiracion_visa_c',
      'label' => 'LBL_FECHA_EXPIRACION_VISA',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'Contacts',
      'type' => 'date',
      'max_size' => NULL,
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-09-17 21:12:44',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Contactsgenero_c' => 
    array (
      'id' => 'Contactsgenero_c',
      'name' => 'genero_c',
      'label' => 'LBL_GENERO',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2018-02-17 13:46:32',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'genero_list',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsidentificacion_australia_c' => 
    array (
      'id' => 'Contactsidentificacion_australia_c',
      'name' => 'identificacion_australia_c',
      'label' => 'LBL_IDENTIFICACION_AUSTRALIA',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-02-17 13:47:04',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsinstitucion_australia_c' => 
    array (
      'id' => 'Contactsinstitucion_australia_c',
      'name' => 'institucion_australia_c',
      'label' => 'LBL_INSTITUCION_AUSTRALIA',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-02-17 13:47:51',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsjjwg_maps_address_c' => 
    array (
      'id' => 'Contactsjjwg_maps_address_c',
      'name' => 'jjwg_maps_address_c',
      'label' => 'LBL_JJWG_MAPS_ADDRESS',
      'comments' => 'Address',
      'help' => 'Address',
      'module' => 'Contacts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2018-02-16 18:47:21',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsjjwg_maps_geocode_status_c' => 
    array (
      'id' => 'Contactsjjwg_maps_geocode_status_c',
      'name' => 'jjwg_maps_geocode_status_c',
      'label' => 'LBL_JJWG_MAPS_GEOCODE_STATUS',
      'comments' => 'Geocode Status',
      'help' => 'Geocode Status',
      'module' => 'Contacts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2018-02-16 18:47:21',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsjjwg_maps_lat_c' => 
    array (
      'id' => 'Contactsjjwg_maps_lat_c',
      'name' => 'jjwg_maps_lat_c',
      'label' => 'LBL_JJWG_MAPS_LAT',
      'comments' => '',
      'help' => 'Latitude',
      'module' => 'Contacts',
      'type' => 'float',
      'max_size' => '10',
      'require_option' => '0',
      'default_value' => '0.00000000',
      'date_modified' => '2018-02-16 18:47:21',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '8',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsjjwg_maps_lng_c' => 
    array (
      'id' => 'Contactsjjwg_maps_lng_c',
      'name' => 'jjwg_maps_lng_c',
      'label' => 'LBL_JJWG_MAPS_LNG',
      'comments' => '',
      'help' => 'Longitude',
      'module' => 'Contacts',
      'type' => 'float',
      'max_size' => '11',
      'require_option' => '0',
      'default_value' => '0.00000000',
      'date_modified' => '2018-02-16 18:47:21',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '8',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsnacimiento_conyuge_c' => 
    array (
      'id' => 'Contactsnacimiento_conyuge_c',
      'name' => 'nacimiento_conyuge_c',
      'label' => 'LBL_NACIMIENTO_CONYUGE',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'date',
      'max_size' => NULL,
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-02-17 13:48:39',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsnivel_ingles_c' => 
    array (
      'id' => 'Contactsnivel_ingles_c',
      'name' => 'nivel_ingles_c',
      'label' => 'LBL_NIVEL_INGLES',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-02-17 13:49:31',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'nivel_ingles_list',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsnombre_conyuge_c' => 
    array (
      'id' => 'Contactsnombre_conyuge_c',
      'name' => 'nombre_conyuge_c',
      'label' => 'LBL_NOMBRE_CONYUGE',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-02-17 13:51:31',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsocupacion_conyuge_c' => 
    array (
      'id' => 'Contactsocupacion_conyuge_c',
      'name' => 'ocupacion_conyuge_c',
      'label' => 'LBL_OCUPACION_CONYUGE',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-02-17 13:52:05',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactspais_c' => 
    array (
      'id' => 'Contactspais_c',
      'name' => 'pais_c',
      'label' => 'LBL_PAIS',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '1',
      'default_value' => 'Colombia',
      'date_modified' => '2018-02-17 13:34:08',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'pais_list',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactspais_nacimiento_c' => 
    array (
      'id' => 'Contactspais_nacimiento_c',
      'name' => 'pais_nacimiento_c',
      'label' => 'LBL_PAIS_NACIMIENTO',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => 'Colombia',
      'date_modified' => '2018-02-17 13:38:29',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'pais_list',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactspasaporte_c' => 
    array (
      'id' => 'Contactspasaporte_c',
      'name' => 'pasaporte_c',
      'label' => 'LBL_PASAPORTE',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '1',
      'default_value' => '',
      'date_modified' => '2018-02-17 13:53:00',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsrelacion_contacto_emergencia_c' => 
    array (
      'id' => 'Contactsrelacion_contacto_emergencia_c',
      'name' => 'relacion_contacto_emergencia_c',
      'label' => 'LBL_RELACION_CONTACTO_EMERGENCIA',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-02-17 13:53:53',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsviajes_realizados_c' => 
    array (
      'id' => 'Contactsviajes_realizados_c',
      'name' => 'viajes_realizados_c',
      'label' => 'LBL_VIAJES_REALIZADOS',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'text',
      'max_size' => NULL,
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-02-17 13:54:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '4',
      'ext3' => '20',
      'ext4' => '',
    ),
    'Contactsvisa_negada_c' => 
    array (
      'id' => 'Contactsvisa_negada_c',
      'name' => 'visa_negada_c',
      'label' => 'LBL_VISA_NEGADA_C',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'bool',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '0',
      'date_modified' => '2018-02-17 13:55:08',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
  ),
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/SearchFields.php',
      'to' => 'custom/modules/Contacts/metadata/SearchFields.php',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/SearchFields.php',
      'to' => 'custom/working/modules/Contacts/metadata/SearchFields.php',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/dashletviewdefs.php',
      'to' => 'custom/modules/Contacts/metadata/dashletviewdefs.php',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/dashletviewdefs.php',
      'to' => 'custom/working/modules/Contacts/metadata/dashletviewdefs.php',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/detailviewdefs.php',
      'to' => 'custom/modules/Contacts/metadata/detailviewdefs.php',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/detailviewdefs.php',
      'to' => 'custom/working/modules/Contacts/metadata/detailviewdefs.php',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/editviewdefs.php',
      'to' => 'custom/modules/Contacts/metadata/editviewdefs.php',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/Contacts/metadata/editviewdefs.php',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/listviewdefs.php',
      'to' => 'custom/modules/Contacts/metadata/listviewdefs.php',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/popupdefs.php',
      'to' => 'custom/modules/Contacts/metadata/popupdefs.php',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/popupdefs.php',
      'to' => 'custom/working/modules/Contacts/metadata/popupdefs.php',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/quickcreatedefs.php',
      'to' => 'custom/modules/Contacts/metadata/quickcreatedefs.php',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/quickcreatedefs.php',
      'to' => 'custom/working/modules/Contacts/metadata/quickcreatedefs.php',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/searchdefs.php',
      'to' => 'custom/modules/Contacts/metadata/searchdefs.php',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/searchdefs.php',
      'to' => 'custom/working/modules/Contacts/metadata/searchdefs.php',
    ),
    15 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Language/en_us.Veta.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Language/en_us.Veta.php',
    ),
    16 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Language/es_ES.Veta.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Language/es_ES.Veta.php',
    ),
    17 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Layoutdefs/veta_ciudadania_contacts_Contacts.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Layoutdefs/veta_ciudadania_contacts_Contacts.php',
    ),
    18 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Layoutdefs/veta_informacionacademica_contacts_Contacts.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Layoutdefs/veta_informacionacademica_contacts_Contacts.php',
    ),
    19 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Layoutdefs/veta_informacionlaboral_contacts_Contacts.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Layoutdefs/veta_informacionlaboral_contacts_Contacts.php',
    ),
    20 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Layoutdefs/veta_otrosnombres_contacts_Contacts.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Layoutdefs/veta_otrosnombres_contacts_Contacts.php',
    ),
    21 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Layoutdefs/veta_visas_contacts_Contacts.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Layoutdefs/veta_visas_contacts_Contacts.php',
    ),
    22 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Layoutdefs/_overrideContact_subpanel_cases.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Layoutdefs/_overrideContact_subpanel_cases.php',
    ),
    23 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Layoutdefs/veta_pasaporte_contacts_Contacts.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Layoutdefs/veta_pasaporte_contacts_Contacts.php',
    ),
    24 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Layoutdefs/veta_solvenciaeconomica_contacts_Contacts.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Layoutdefs/veta_solvenciaeconomica_contacts_Contacts.php',
    ),
    25 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Layoutdefs/veta_serviciosadicionales_contacts_Contacts.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Layoutdefs/veta_serviciosadicionales_contacts_Contacts.php',
    ),
    26 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Layoutdefs/veta_hijo_contacts_Contacts.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Layoutdefs/veta_hijo_contacts_Contacts.php',
    ),
    27 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Layoutdefs/removesubpanel.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Layoutdefs/removesubpanel.php',
    ),
    28 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_last_name.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_last_name.php',
    ),
    29 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/veta_ciudadania_contacts_Contacts.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/veta_ciudadania_contacts_Contacts.php',
    ),
    30 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/veta_informacionacademica_contacts_Contacts.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/veta_informacionacademica_contacts_Contacts.php',
    ),
    31 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/veta_informacionlaboral_contacts_Contacts.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/veta_informacionlaboral_contacts_Contacts.php',
    ),
    32 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/veta_otrosnombres_contacts_Contacts.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/veta_otrosnombres_contacts_Contacts.php',
    ),
    33 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_genero_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_genero_c.php',
    ),
    34 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_jjwg_maps_geocode_status_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_jjwg_maps_geocode_status_c.php',
    ),
    35 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_deleted.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_deleted.php',
    ),
    36 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_departamento_nacimiento_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_departamento_nacimiento_c.php',
    ),
    37 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_cuenta_bancaria_australia_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_cuenta_bancaria_australia_c.php',
    ),
    38 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_nacimiento_conyuge_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_nacimiento_conyuge_c.php',
    ),
    39 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_fecha_expiracion_visa_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_fecha_expiracion_visa_c.php',
    ),
    40 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_description.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_description.php',
    ),
    41 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_email_contacto_emergencia_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_email_contacto_emergencia_c.php',
    ),
    42 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_ocupacion_conyuge_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_ocupacion_conyuge_c.php',
    ),
    43 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_jjwg_maps_lat_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_jjwg_maps_lat_c.php',
    ),
    44 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_edad_conyuge_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_edad_conyuge_c.php',
    ),
    45 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_department.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_department.php',
    ),
    46 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_birthdate.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_birthdate.php',
    ),
    47 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_email1.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_email1.php',
    ),
    48 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_ciudad_nacimiento_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_ciudad_nacimiento_c.php',
    ),
    49 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/veta_visas_contacts_Contacts.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/veta_visas_contacts_Contacts.php',
    ),
    50 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_pais_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_pais_c.php',
    ),
    51 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_celular_contacto_emergencia_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_celular_contacto_emergencia_c.php',
    ),
    52 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/veta_pasaporte_contacts_Contacts.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/veta_pasaporte_contacts_Contacts.php',
    ),
    53 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_pasaporte_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_pasaporte_c.php',
    ),
    54 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_anos_sin_estudiar_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_anos_sin_estudiar_c.php',
    ),
    55 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_departamento_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_departamento_c.php',
    ),
    56 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_institucion_australia_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_institucion_australia_c.php',
    ),
    57 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_ciudad_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_ciudad_c.php',
    ),
    58 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/veta_solvenciaeconomica_contacts_Contacts.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/veta_solvenciaeconomica_contacts_Contacts.php',
    ),
    59 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_edad_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_edad_c.php',
    ),
    60 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_first_name.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_first_name.php',
    ),
    61 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/veta_serviciosadicionales_contacts_Contacts.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/veta_serviciosadicionales_contacts_Contacts.php',
    ),
    62 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_viajes_realizados_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_viajes_realizados_c.php',
    ),
    63 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_pais_nacimiento_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_pais_nacimiento_c.php',
    ),
    64 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_estado_civil_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_estado_civil_c.php',
    ),
    65 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_direccion_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_direccion_c.php',
    ),
    66 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_celular_autralia_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_celular_autralia_c.php',
    ),
    67 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_nombre_conyuge_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_nombre_conyuge_c.php',
    ),
    68 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/veta_hijo_contacts_Contacts.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/veta_hijo_contacts_Contacts.php',
    ),
    69 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_title.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_title.php',
    ),
    70 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_contacto_emergencia_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_contacto_emergencia_c.php',
    ),
    71 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_nivel_ingles_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_nivel_ingles_c.php',
    ),
    72 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_identificacion_australia_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_identificacion_australia_c.php',
    ),
    73 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_visa_negada_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_visa_negada_c.php',
    ),
    74 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_relacion_contacto_emergencia_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_relacion_contacto_emergencia_c.php',
    ),
    75 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_lead_source.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_lead_source.php',
    ),
    76 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_jjwg_maps_lng_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_jjwg_maps_lng_c.php',
    ),
    77 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_jjwg_maps_address_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_jjwg_maps_address_c.php',
    ),
  ),
);