<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2017 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */



// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '6.5.25',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => '',
  'author' => '',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Leads',
  'published_date' => '2019-10-09 17:27:58',
  'type' => 'module',
  'version' => 1570642079,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'Leads',
  'relationships' => 
  array (
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/include/language/en_us.Leads.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/include/language/es_ES.Leads.php',
      'to_module' => 'application',
      'language' => 'es_ES',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/language/en_us.lang.php',
      'to_module' => 'Leads',
      'language' => 'en_us',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/language/es_ES.lang.php',
      'to_module' => 'Leads',
      'language' => 'es_ES',
    ),
  ),
  'custom_fields' => 
  array (
    'Leadsanos_sin_estudiar_c' => 
    array (
      'id' => 'Leadsanos_sin_estudiar_c',
      'name' => 'anos_sin_estudiar_c',
      'label' => 'LBL_ANOS_SIN_ESTUDIAR',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'int',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '0',
      'date_modified' => '2018-02-16 18:53:01',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '0',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadscampaign_id_c' => 
    array (
      'id' => 'Leadscampaign_id_c',
      'name' => 'campaign_id_c',
      'label' => 'LBL_CAMPANA_CAMPAIGN_ID',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2018-02-16 18:54:04',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadscampana_c' => 
    array (
      'id' => 'Leadscampana_c',
      'name' => 'campana_c',
      'label' => 'LBL_CAMPANA',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'Leads',
      'type' => 'relate',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-09-18 15:10:41',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => 'Campaigns',
      'ext3' => 'campaign_id_c',
      'ext4' => NULL,
    ),
    'Leadscargo_c' => 
    array (
      'id' => 'Leadscargo_c',
      'name' => 'cargo_c',
      'label' => 'LBL_CARGO',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-02-16 18:54:53',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadsciudad_c' => 
    array (
      'id' => 'Leadsciudad_c',
      'name' => 'ciudad_c',
      'label' => 'LBL_CIUDAD',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'dynamicenum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2018-02-16 19:05:35',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'ciudades_list',
      'ext2' => 'departamento_c',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadscurrency_id' => 
    array (
      'id' => 'Leadscurrency_id',
      'name' => 'currency_id',
      'label' => 'LBL_CURRENCY',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'currency_id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2018-02-16 19:16:35',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadsdepartamento_c' => 
    array (
      'id' => 'Leadsdepartamento_c',
      'name' => 'departamento_c',
      'label' => 'LBL_DEPARTAMENTO',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'dynamicenum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2018-02-16 19:04:35',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'departamentos_list',
      'ext2' => 'pais_c',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadsedad_c' => 
    array (
      'id' => 'Leadsedad_c',
      'name' => 'edad_c',
      'label' => 'LBL_EDAD',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'Leads',
      'type' => 'int',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '0',
      'date_modified' => '2019-08-21 01:56:26',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '0',
      'ext2' => '200',
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Leadsedad_conyuge_c' => 
    array (
      'id' => 'Leadsedad_conyuge_c',
      'name' => 'edad_conyuge_c',
      'label' => 'LBL_EDAD_CONYUGE',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'int',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-02-16 19:07:16',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadsfecha_cotizacion_c' => 
    array (
      'id' => 'Leadsfecha_cotizacion_c',
      'name' => 'fecha_cotizacion_c',
      'label' => 'LBL_FECHA_COTIZACION',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'date',
      'max_size' => NULL,
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-02-16 19:08:10',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadsfecha_expiracion_visa_c' => 
    array (
      'id' => 'Leadsfecha_expiracion_visa_c',
      'name' => 'fecha_expiracion_visa_c',
      'label' => 'LBL_FECHA_EXPIRACION_VISA',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'datetimecombo',
      'max_size' => NULL,
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2019-09-26 20:01:50',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '1',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadsfecha_proximo_contacto_c' => 
    array (
      'id' => 'Leadsfecha_proximo_contacto_c',
      'name' => 'fecha_proximo_contacto_c',
      'label' => 'LBL_FECHA_PROXIMO_CONTACTO',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'date',
      'max_size' => NULL,
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-02-16 19:08:56',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadsfecha_ultimo_contacto_c' => 
    array (
      'id' => 'Leadsfecha_ultimo_contacto_c',
      'name' => 'fecha_ultimo_contacto_c',
      'label' => 'LBL_FECHA_ULTIMO_CONTACTO',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'date',
      'max_size' => NULL,
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-02-16 19:09:38',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadsfecha_viaje_c' => 
    array (
      'id' => 'Leadsfecha_viaje_c',
      'name' => 'fecha_viaje_c',
      'label' => 'LBL_FECHA_VIAJE',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'date',
      'max_size' => NULL,
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-02-16 19:10:45',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadshijos_c' => 
    array (
      'id' => 'Leadshijos_c',
      'name' => 'hijos_c',
      'label' => 'LBL_HIJOS',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'Leads',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-07-15 20:38:11',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Leadsjjwg_maps_address_c' => 
    array (
      'id' => 'Leadsjjwg_maps_address_c',
      'name' => 'jjwg_maps_address_c',
      'label' => 'LBL_JJWG_MAPS_ADDRESS',
      'comments' => 'Address',
      'help' => 'Address',
      'module' => 'Leads',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2018-02-16 18:47:21',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadsjjwg_maps_geocode_status_c' => 
    array (
      'id' => 'Leadsjjwg_maps_geocode_status_c',
      'name' => 'jjwg_maps_geocode_status_c',
      'label' => 'LBL_JJWG_MAPS_GEOCODE_STATUS',
      'comments' => 'Geocode Status',
      'help' => 'Geocode Status',
      'module' => 'Leads',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2018-02-16 18:47:21',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadsjjwg_maps_lat_c' => 
    array (
      'id' => 'Leadsjjwg_maps_lat_c',
      'name' => 'jjwg_maps_lat_c',
      'label' => 'LBL_JJWG_MAPS_LAT',
      'comments' => '',
      'help' => 'Latitude',
      'module' => 'Leads',
      'type' => 'float',
      'max_size' => '10',
      'require_option' => '0',
      'default_value' => '0.00000000',
      'date_modified' => '2018-02-16 18:47:21',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '8',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadsjjwg_maps_lng_c' => 
    array (
      'id' => 'Leadsjjwg_maps_lng_c',
      'name' => 'jjwg_maps_lng_c',
      'label' => 'LBL_JJWG_MAPS_LNG',
      'comments' => '',
      'help' => 'Longitude',
      'module' => 'Leads',
      'type' => 'float',
      'max_size' => '11',
      'require_option' => '0',
      'default_value' => '0.00000000',
      'date_modified' => '2018-02-16 18:47:21',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '8',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadsnacimiento_conyuge_c' => 
    array (
      'id' => 'Leadsnacimiento_conyuge_c',
      'name' => 'nacimiento_conyuge_c',
      'label' => 'LBL_NACIMIENTO_CONYUGE',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'date',
      'max_size' => NULL,
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-02-16 19:12:07',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadsnombre_conyuge_c' => 
    array (
      'id' => 'Leadsnombre_conyuge_c',
      'name' => 'nombre_conyuge_c',
      'label' => 'LBL_NOMBRE_CONYUGE',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-02-16 19:12:44',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadsocupacion_conyuge_c' => 
    array (
      'id' => 'Leadsocupacion_conyuge_c',
      'name' => 'ocupacion_conyuge_c',
      'label' => 'LBL_OCUPACION_CONYUGE',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-02-16 19:13:32',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadsok_comercial_c' => 
    array (
      'id' => 'Leadsok_comercial_c',
      'name' => 'ok_comercial_c',
      'label' => 'LBL_OK_COMERCIAL',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'bool',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '0',
      'date_modified' => '2018-02-16 19:14:20',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadsok_visas_c' => 
    array (
      'id' => 'Leadsok_visas_c',
      'name' => 'ok_visas_c',
      'label' => 'LBL_OK_VISAS',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'bool',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '0',
      'date_modified' => '2018-02-16 19:15:06',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadspais_c' => 
    array (
      'id' => 'Leadspais_c',
      'name' => 'pais_c',
      'label' => 'LBL_PAIS',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => 'Colombia',
      'date_modified' => '2018-02-16 19:03:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'pais_list',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadspasaporte_c' => 
    array (
      'id' => 'Leadspasaporte_c',
      'name' => 'pasaporte_c',
      'label' => 'LBL_PASAPORTE',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-02-16 19:15:45',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadspresupuesto_c' => 
    array (
      'id' => 'Leadspresupuesto_c',
      'name' => 'presupuesto_c',
      'label' => 'LBL_PRESUPUESTO',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'currency',
      'max_size' => '26',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-02-16 19:16:35',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
  ),
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/metadata/SearchFields.php',
      'to' => 'custom/modules/Leads/metadata/SearchFields.php',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/metadata/SearchFields.php',
      'to' => 'custom/working/modules/Leads/metadata/SearchFields.php',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/metadata/convertdefs.php',
      'to' => 'custom/modules/Leads/metadata/convertdefs.php',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/metadata/convertdefs.php',
      'to' => 'custom/working/modules/Leads/metadata/convertdefs.php',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/metadata/dashletviewdefs.php',
      'to' => 'custom/modules/Leads/metadata/dashletviewdefs.php',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/metadata/dashletviewdefs.php',
      'to' => 'custom/working/modules/Leads/metadata/dashletviewdefs.php',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/metadata/detailviewdefs.php',
      'to' => 'custom/modules/Leads/metadata/detailviewdefs.php',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/metadata/detailviewdefs.php',
      'to' => 'custom/working/modules/Leads/metadata/detailviewdefs.php',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/metadata/editviewdefs.php',
      'to' => 'custom/modules/Leads/metadata/editviewdefs.php',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/Leads/metadata/editviewdefs.php',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/metadata/listviewdefs.php',
      'to' => 'custom/modules/Leads/metadata/listviewdefs.php',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/metadata/popupdefs.php',
      'to' => 'custom/modules/Leads/metadata/popupdefs.php',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/metadata/popupdefs.php',
      'to' => 'custom/working/modules/Leads/metadata/popupdefs.php',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/metadata/quickcreatedefs.php',
      'to' => 'custom/modules/Leads/metadata/quickcreatedefs.php',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/metadata/quickcreatedefs.php',
      'to' => 'custom/working/modules/Leads/metadata/quickcreatedefs.php',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/metadata/searchdefs.php',
      'to' => 'custom/modules/Leads/metadata/searchdefs.php',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/metadata/searchdefs.php',
      'to' => 'custom/working/modules/Leads/metadata/searchdefs.php',
    ),
    17 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Language/en_us.Veta.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Language/en_us.Veta.php',
    ),
    18 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Language/es_ES.Veta.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Language/es_ES.Veta.php',
    ),
    19 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Layoutdefs/veta_visas_leads_Leads.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Layoutdefs/veta_visas_leads_Leads.php',
    ),
    20 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Layoutdefs/veta_informacionlaboral_leads_Leads.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Layoutdefs/veta_informacionlaboral_leads_Leads.php',
    ),
    21 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Layoutdefs/veta_ciudadania_leads_Leads.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Layoutdefs/veta_ciudadania_leads_Leads.php',
    ),
    22 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Layoutdefs/veta_pasaporte_leads_Leads.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Layoutdefs/veta_pasaporte_leads_Leads.php',
    ),
    23 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Layoutdefs/veta_otrosnombres_leads_Leads.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Layoutdefs/veta_otrosnombres_leads_Leads.php',
    ),
    24 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Layoutdefs/veta_serviciosadicionales_leads_Leads.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Layoutdefs/veta_serviciosadicionales_leads_Leads.php',
    ),
    25 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Layoutdefs/veta_informacionacademica_leads_Leads.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Layoutdefs/veta_informacionacademica_leads_Leads.php',
    ),
    26 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Layoutdefs/veta_solvenciaeconomica_leads_Leads.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Layoutdefs/veta_solvenciaeconomica_leads_Leads.php',
    ),
    27 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_last_name.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_last_name.php',
    ),
    28 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_status_description.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_status_description.php',
    ),
    29 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/veta_visas_leads_Leads.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/veta_visas_leads_Leads.php',
    ),
    30 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_salutation.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_salutation.php',
    ),
    31 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_campaign_id_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_campaign_id_c.php',
    ),
    32 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/veta_informacionlaboral_leads_Leads.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/veta_informacionlaboral_leads_Leads.php',
    ),
    33 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_jjwg_maps_geocode_status_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_jjwg_maps_geocode_status_c.php',
    ),
    34 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_deleted.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_deleted.php',
    ),
    35 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_fecha_proximo_contacto_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_fecha_proximo_contacto_c.php',
    ),
    36 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_fecha_viaje_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_fecha_viaje_c.php',
    ),
    37 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/veta_ciudadania_leads_Leads.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/veta_ciudadania_leads_Leads.php',
    ),
    38 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_nacimiento_conyuge_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_nacimiento_conyuge_c.php',
    ),
    39 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_fecha_expiracion_visa_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_fecha_expiracion_visa_c.php',
    ),
    40 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_ocupacion_conyuge_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_ocupacion_conyuge_c.php',
    ),
    41 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_jjwg_maps_lat_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_jjwg_maps_lat_c.php',
    ),
    42 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/veta_pasaporte_leads_Leads.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/veta_pasaporte_leads_Leads.php',
    ),
    43 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/veta_otrosnombres_leads_Leads.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/veta_otrosnombres_leads_Leads.php',
    ),
    44 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_edad_conyuge_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_edad_conyuge_c.php',
    ),
    45 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_presupuesto_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_presupuesto_c.php',
    ),
    46 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_fecha_cotizacion_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_fecha_cotizacion_c.php',
    ),
    47 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_birthdate.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_birthdate.php',
    ),
    48 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_email1.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_email1.php',
    ),
    49 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/veta_serviciosadicionales_leads_Leads.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/veta_serviciosadicionales_leads_Leads.php',
    ),
    50 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_cargo_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_cargo_c.php',
    ),
    51 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_ok_comercial_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_ok_comercial_c.php',
    ),
    52 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_pais_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_pais_c.php',
    ),
    53 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_hijos_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_hijos_c.php',
    ),
    54 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_currency_id.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_currency_id.php',
    ),
    55 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_pasaporte_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_pasaporte_c.php',
    ),
    56 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_anos_sin_estudiar_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_anos_sin_estudiar_c.php',
    ),
    57 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_departamento_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_departamento_c.php',
    ),
    58 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_fecha_ultimo_contacto_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_fecha_ultimo_contacto_c.php',
    ),
    59 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/veta_informacionacademica_leads_Leads.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/veta_informacionacademica_leads_Leads.php',
    ),
    60 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_ciudad_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_ciudad_c.php',
    ),
    61 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_edad_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_edad_c.php',
    ),
    62 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_ok_visas_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_ok_visas_c.php',
    ),
    63 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_first_name.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_first_name.php',
    ),
    64 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_converted.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_converted.php',
    ),
    65 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_nombre_conyuge_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_nombre_conyuge_c.php',
    ),
    66 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_title.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_title.php',
    ),
    67 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/veta_solvenciaeconomica_leads_Leads.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/veta_solvenciaeconomica_leads_Leads.php',
    ),
    68 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_campana_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_campana_c.php',
    ),
    69 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_lead_source.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_lead_source.php',
    ),
    70 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_status.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_status.php',
    ),
    71 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_jjwg_maps_lng_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_jjwg_maps_lng_c.php',
    ),
    72 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_jjwg_maps_address_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_jjwg_maps_address_c.php',
    ),
    73 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_date_modified.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_date_modified.php',
    ),
  ),
);