<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'Doc',
  'author' => 'Eticco',
  'description' => 'Modulos parte portal documentos',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Documentos',
  'published_date' => '2021-06-14 20:29:51',
  'type' => 'module',
  'version' => 1623702591,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'Documentos',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'Doc_Comentarios',
      'class' => 'Doc_Comentarios',
      'path' => 'modules/Doc_Comentarios/Doc_Comentarios.php',
      'tab' => true,
    ),
    1 => 
    array (
      'module' => 'Doc_DocsSolicitados',
      'class' => 'Doc_DocsSolicitados',
      'path' => 'modules/Doc_DocsSolicitados/Doc_DocsSolicitados.php',
      'tab' => true,
    ),
    2 => 
    array (
      'module' => 'Doc_Plantillas',
      'class' => 'Doc_Plantillas',
      'path' => 'modules/Doc_Plantillas/Doc_Plantillas.php',
      'tab' => true,
    ),
    3 => 
    array (
      'module' => 'Doc_Documentos',
      'class' => 'Doc_Documentos',
      'path' => 'modules/Doc_Documentos/Doc_Documentos.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/doc_comentarios_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/doc_docssolicitados_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/doc_docssolicitados_doc_documentos_Doc_DocsSolicitados.php',
      'to_module' => 'Doc_DocsSolicitados',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/doc_plantillas_doc_documentos_Doc_Documentos.php',
      'to_module' => 'Doc_Documentos',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/doc_plantillas_doc_documentos_Doc_Plantillas.php',
      'to_module' => 'Doc_Plantillas',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/doc_plantillas_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/doc_plantillas_opportunities_Doc_Plantillas.php',
      'to_module' => 'Doc_Plantillas',
    ),
  ),
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/doc_comentarios_opportunitiesMetaData.php',
    ),
    1 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/doc_docssolicitados_opportunitiesMetaData.php',
    ),
    2 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/doc_docssolicitados_doc_documentosMetaData.php',
    ),
    3 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/doc_plantillas_doc_documentosMetaData.php',
    ),
    4 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/doc_plantillas_opportunitiesMetaData.php',
    ),
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Doc_Comentarios',
      'to' => 'modules/Doc_Comentarios',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Doc_DocsSolicitados',
      'to' => 'modules/Doc_DocsSolicitados',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Doc_Plantillas',
      'to' => 'modules/Doc_Plantillas',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Doc_Documentos',
      'to' => 'modules/Doc_Documentos',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Doc_Comentarios.php',
      'to_module' => 'Doc_Comentarios',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Doc_Comentarios.php',
      'to_module' => 'Doc_Comentarios',
      'language' => 'es_ES',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'en_us',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'es_ES',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Doc_DocsSolicitados.php',
      'to_module' => 'Doc_DocsSolicitados',
      'language' => 'en_us',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Doc_DocsSolicitados.php',
      'to_module' => 'Doc_DocsSolicitados',
      'language' => 'es_ES',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'en_us',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'es_ES',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Doc_Documentos.php',
      'to_module' => 'Doc_Documentos',
      'language' => 'en_us',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Doc_Documentos.php',
      'to_module' => 'Doc_Documentos',
      'language' => 'es_ES',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Doc_DocsSolicitados.php',
      'to_module' => 'Doc_DocsSolicitados',
      'language' => 'en_us',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Doc_DocsSolicitados.php',
      'to_module' => 'Doc_DocsSolicitados',
      'language' => 'es_ES',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Doc_Documentos.php',
      'to_module' => 'Doc_Documentos',
      'language' => 'en_us',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Doc_Documentos.php',
      'to_module' => 'Doc_Documentos',
      'language' => 'es_ES',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Doc_Plantillas.php',
      'to_module' => 'Doc_Plantillas',
      'language' => 'en_us',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Doc_Plantillas.php',
      'to_module' => 'Doc_Plantillas',
      'language' => 'es_ES',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'en_us',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'es_ES',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Doc_Plantillas.php',
      'to_module' => 'Doc_Plantillas',
      'language' => 'en_us',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Doc_Plantillas.php',
      'to_module' => 'Doc_Plantillas',
      'language' => 'es_ES',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/es_ES.lang.php',
      'to_module' => 'application',
      'language' => 'es_ES',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),
  'vardefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/doc_comentarios_opportunities_Doc_Comentarios.php',
      'to_module' => 'Doc_Comentarios',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/doc_comentarios_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/doc_docssolicitados_opportunities_Doc_DocsSolicitados.php',
      'to_module' => 'Doc_DocsSolicitados',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/doc_docssolicitados_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/doc_docssolicitados_doc_documentos_Doc_Documentos.php',
      'to_module' => 'Doc_Documentos',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/doc_docssolicitados_doc_documentos_Doc_DocsSolicitados.php',
      'to_module' => 'Doc_DocsSolicitados',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/doc_plantillas_doc_documentos_Doc_Documentos.php',
      'to_module' => 'Doc_Documentos',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/doc_plantillas_doc_documentos_Doc_Plantillas.php',
      'to_module' => 'Doc_Plantillas',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/doc_plantillas_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/doc_plantillas_opportunities_Doc_Plantillas.php',
      'to_module' => 'Doc_Plantillas',
    ),
  ),
  'layoutfields' => 
  array (
    0 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    1 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    2 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
  ),
);