<?php

class OpportunitiesViewDetail extends ViewDetail
{
    public function __construct()
    {
        parent::__construct();
    }

    public function display()
    {
        $this->load_info();
        $this->load_lead_info();
        $this->load_contact_info();

        $this->ss->assign("REQUERIMIENTO", $this->REQUERIMIENTO);
        $this->ss->assign("IDREQUERIMIENTO", $this->IDREQUERIMIENTO);
        $this->ss->assign("soel_mobile_phone_lead", $this->soel_mobile_phone_lead);
        $this->ss->assign("soel_email_lead", $this->soel_email_lead);
        

        parent::display();
    }

    public function _displaySubPanels()
    {
        $this->bean->email1 = $this->EMAIL;
        $this->bean->name =  $this->NOMBRE;        
        parent::_displaySubPanels(); // TODO: Change the autogenerated stub
    }

    /**
     * Carga informaciòn del requerimiento asociado a la oportunidad
     */
    private function load_info()
    {
        $query = "SELECT DISTINCT veta_requerimiento.id, veta_requerimiento.name                    
                 FROM opportunities venta   
                 LEFT JOIN veta_recibo_opportunities_c ON veta_recibo_opportunities_c.veta_recibo_opportunitiesopportunities_idb = venta.id AND veta_recibo_opportunities_c.deleted =0
                 LEFT JOIN veta_requerimiento_veta_recibo_c ON veta_requerimiento_veta_recibo_c.veta_requerimiento_veta_reciboveta_recibo_idb = veta_recibo_opportunities_c.veta_recibo_opportunitiesveta_recibo_ida AND veta_requerimiento_veta_recibo_c.deleted = 0
                 LEFT JOIN veta_requerimiento ON veta_requerimiento.id = veta_requerimiento_veta_recibo_c.veta_requerimiento_veta_reciboveta_requerimiento_ida AND veta_requerimiento.deleted = 0 
                 WHERE venta.deleted = 0 AND venta.id = '" . $this->bean->id . "'";

        $result = $this->bean->db->query($query, true, "Error obteniendo informacion del requerimiento asociado a la oportunidad " . $this->bean->id);
        $row = $this->bean->db->fetchByAssoc($result);

        if ($row != null) {

            $this->IDREQUERIMIENTO = $row['id'];
            $this->REQUERIMIENTO = $row['name'];
        }
    }

    /**
     * Carga información adicional que tiene como origen el prospecto
     */
    private function load_lead_info()
    {
        $query = "SELECT 
                    leads.id AS ID, 
                    CONCAT(leads.first_name, ' ' , leads.last_name) AS NOMBRE,
                    leads.phone_mobile as CELULAR                 
                 FROM opportunities venta   
                    LEFT JOIN veta_recibo_opportunities_c ON veta_recibo_opportunities_c.veta_recibo_opportunitiesopportunities_idb = venta.id AND veta_recibo_opportunities_c.deleted =0
                    LEFT JOIN veta_requerimiento_veta_recibo_c ON veta_requerimiento_veta_recibo_c.veta_requerimiento_veta_reciboveta_recibo_idb = veta_recibo_opportunities_c.veta_recibo_opportunitiesveta_recibo_ida AND veta_requerimiento_veta_recibo_c.deleted = 0
                    LEFT JOIN veta_requerimiento ON veta_requerimiento.id = veta_requerimiento_veta_recibo_c.veta_requerimiento_veta_reciboveta_requerimiento_ida AND veta_requerimiento.deleted = 0
                    INNER JOIN veta_requerimiento_leads_c ON veta_requerimiento_leads_c.veta_requerimiento_leadsveta_requerimiento_idb = veta_requerimiento.id AND veta_requerimiento_leads_c.deleted = 0
                    INNER JOIN leads ON leads.id = veta_requerimiento_leads_c.veta_requerimiento_leadsleads_ida AND leads.deleted = 0
                 WHERE venta.deleted = 0 AND venta.id = '" . $this->bean->id . "'";

        $result = $this->bean->db->query($query, true,"Error obteniendo informacion del prospecto asociado al requerimiento " . $this->bean->id );
        $row = $this->bean->db->fetchByAssoc($result);

        if ($row != null) {
            $lead = new Lead();
            $lead->retrieve($row['ID']);

            $this->EMAIL = $lead->email1;
            $this->NOMBRE = $row['NOMBRE'];
            $this->soel_mobile_phone_lead = $row['CELULAR'];
            $this->soel_email_lead = $lead->email1;
        }
    }

    private function load_contact_info()
    {
        $query = "SELECT 
                    contacts.id AS ID, 
                    CONCAT(contacts.first_name, ' ' , contacts.last_name) AS NOMBRE                                                       
               FROM opportunities venta   
                    LEFT JOIN veta_recibo_opportunities_c ON veta_recibo_opportunities_c.veta_recibo_opportunitiesopportunities_idb = venta.id AND veta_recibo_opportunities_c.deleted =0
                    LEFT JOIN veta_requerimiento_veta_recibo_c ON veta_requerimiento_veta_recibo_c.veta_requerimiento_veta_reciboveta_recibo_idb = veta_recibo_opportunities_c.veta_recibo_opportunitiesveta_recibo_ida AND veta_requerimiento_veta_recibo_c.deleted = 0
                    LEFT JOIN veta_requerimiento ON veta_requerimiento.id = veta_requerimiento_veta_recibo_c.veta_requerimiento_veta_reciboveta_requerimiento_ida AND veta_requerimiento.deleted = 0
                    INNER JOIN veta_requerimiento_contacts_c ON veta_requerimiento_contacts_c.veta_requerimiento_contactsveta_requerimiento_idb = veta_requerimiento.id AND veta_requerimiento_contacts_c.deleted = 0
                    INNER JOIN contacts ON contacts.id = veta_requerimiento_contacts_c.veta_requerimiento_contactscontacts_ida AND contacts.deleted = 0
                 WHERE venta.deleted = 0 AND venta.id = '" . $this->bean->id . "'";

        $result = $this->bean->db->query($query, true,"Error obteniendo informacion del contacto asociado al requerimiento " . $this->bean->id );
        $row = $this->bean->db->fetchByAssoc($result);

        if ($row != null) {
            $contact = new Contact();
            $contact->retrieve($row['ID']);

            $this->EMAIL = empty($this->EMAIL) ? $contact->email1 : $this->EMAIL;
            $this->NOMBRE = $row['NOMBRE'];
            $this->soel_mobile_phone_lead = empty($this->soel_mobile_phone_lead) ? $row['CELULAR'] : $this->EMAIL;
            $this->soel_email_lead = $this->EMAIL;
        }
    }
}
