<?php

require_once( 'include/MVC/View/views/view.detail.php' );

class LeadsViewDetail extends ViewDetail
{


    function preDisplay()
    {
        parent::preDisplay(); // TODO: Change the autogenerated stub
    }


}