<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'Veta',
  'author' => 'SOEL',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Veta',
  'published_date' => '2019-10-15 18:09:42',
  'type' => 'module',
  'version' => 1571162982,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'Veta',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'Veta_PagoColegios',
      'class' => 'Veta_PagoColegios',
      'path' => 'modules/Veta_PagoColegios/Veta_PagoColegios.php',
      'tab' => true,
    ),
    1 => 
    array (
      'module' => 'Veta_Visa',
      'class' => 'Veta_Visa',
      'path' => 'modules/Veta_Visa/Veta_Visa.php',
      'tab' => true,
    ),
    2 => 
    array (
      'module' => 'Veta_Pagos',
      'class' => 'Veta_Pagos',
      'path' => 'modules/Veta_Pagos/Veta_Pagos.php',
      'tab' => true,
    ),
    3 => 
    array (
      'module' => 'Veta_NotificacionPagoColegio',
      'class' => 'Veta_NotificacionPagoColegio',
      'path' => 'modules/Veta_NotificacionPagoColegio/Veta_NotificacionPagoColegio.php',
      'tab' => true,
    ),
    4 => 
    array (
      'module' => 'Veta_Aplicacion',
      'class' => 'Veta_Aplicacion',
      'path' => 'modules/Veta_Aplicacion/Veta_Aplicacion.php',
      'tab' => true,
    ),
    5 => 
    array (
      'module' => 'Veta_ABNTaxFile',
      'class' => 'Veta_ABNTaxFile',
      'path' => 'modules/Veta_ABNTaxFile/Veta_ABNTaxFile.php',
      'tab' => true,
    ),
    6 => 
    array (
      'module' => 'Veta_COE',
      'class' => 'Veta_COE',
      'path' => 'modules/Veta_COE/Veta_COE.php',
      'tab' => true,
    ),
    7 => 
    array (
      'module' => 'Veta_LooCorreccion',
      'class' => 'Veta_LooCorreccion',
      'path' => 'modules/Veta_LooCorreccion/Veta_LooCorreccion.php',
      'tab' => true,
    ),
    8 => 
    array (
      'module' => 'Veta_Loo',
      'class' => 'Veta_Loo',
      'path' => 'modules/Veta_Loo/Veta_Loo.php',
      'tab' => true,
    ),
    9 => 
    array (
      'module' => 'Veta_Liquidacion',
      'class' => 'Veta_Liquidacion',
      'path' => 'modules/Veta_Liquidacion/Veta_Liquidacion.php',
      'tab' => true,
    ),
    10 => 
    array (
      'module' => 'Veta_CorreccionCOE',
      'class' => 'Veta_CorreccionCOE',
      'path' => 'modules/Veta_CorreccionCOE/Veta_CorreccionCOE.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/veta_pagocolegios_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/veta_pagocolegios_activities_calls_Veta_PagoColegios.php',
      'to_module' => 'Veta_PagoColegios',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/veta_visa_veta_coe_Veta_COE.php',
      'to_module' => 'Veta_COE',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/veta_visa_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/veta_visa_cases_Veta_Visa.php',
      'to_module' => 'Veta_Visa',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/veta_pagos_veta_liquidacion_Veta_Liquidacion.php',
      'to_module' => 'Veta_Liquidacion',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/veta_notificacionpagocolegio_veta_pagocolegios_Veta_PagoColegios.php',
      'to_module' => 'Veta_PagoColegios',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/veta_aplicacion_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/veta_aplicacion_cases_Veta_Aplicacion.php',
      'to_module' => 'Veta_Aplicacion',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/veta_aplicacion_activities_calls_Veta_Aplicacion.php',
      'to_module' => 'Veta_Aplicacion',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/veta_coe_veta_aplicacion_Veta_Aplicacion.php',
      'to_module' => 'Veta_Aplicacion',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/veta_coe_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/veta_coe_cases_Veta_COE.php',
      'to_module' => 'Veta_COE',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/veta_coe_activities_calls_Veta_COE.php',
      'to_module' => 'Veta_COE',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/veta_loocorreccion_veta_loo_Veta_Loo.php',
      'to_module' => 'Veta_Loo',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/veta_loo_veta_aplicacion_Veta_Aplicacion.php',
      'to_module' => 'Veta_Aplicacion',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/veta_loo_cases_Veta_Loo.php',
      'to_module' => 'Veta_Loo',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/veta_loo_activities_calls_Veta_Loo.php',
      'to_module' => 'Veta_Loo',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/veta_liquidacion_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/veta_liquidacion_cases_Veta_Liquidacion.php',
      'to_module' => 'Veta_Liquidacion',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/veta_liquidacion_activities_calls_Veta_Liquidacion.php',
      'to_module' => 'Veta_Liquidacion',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/veta_correccioncoe_veta_coe_Veta_COE.php',
      'to_module' => 'Veta_COE',
    ),
  ),
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_pagocolegios_opportunitiesMetaData.php',
    ),
    1 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_pagocolegios_activities_callsMetaData.php',
    ),
    2 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_pagocolegios_activities_meetingsMetaData.php',
    ),
    3 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_pagocolegios_activities_notesMetaData.php',
    ),
    4 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_pagocolegios_activities_tasksMetaData.php',
    ),
    5 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_pagocolegios_activities_emailsMetaData.php',
    ),
    6 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_visa_veta_coeMetaData.php',
    ),
    7 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_visa_opportunitiesMetaData.php',
    ),
    8 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_visa_casesMetaData.php',
    ),
    9 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_pagos_veta_liquidacionMetaData.php',
    ),
    10 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_notificacionpagocolegio_veta_pagocolegiosMetaData.php',
    ),
    11 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_aplicacion_opportunitiesMetaData.php',
    ),
    12 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_aplicacion_casesMetaData.php',
    ),
    13 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_aplicacion_activities_callsMetaData.php',
    ),
    14 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_aplicacion_activities_meetingsMetaData.php',
    ),
    15 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_aplicacion_activities_notesMetaData.php',
    ),
    16 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_aplicacion_activities_tasksMetaData.php',
    ),
    17 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_aplicacion_activities_emailsMetaData.php',
    ),
    18 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_coe_veta_aplicacionMetaData.php',
    ),
    19 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_coe_opportunitiesMetaData.php',
    ),
    20 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_coe_casesMetaData.php',
    ),
    21 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_coe_activities_callsMetaData.php',
    ),
    22 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_coe_activities_meetingsMetaData.php',
    ),
    23 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_coe_activities_notesMetaData.php',
    ),
    24 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_coe_activities_tasksMetaData.php',
    ),
    25 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_coe_activities_emailsMetaData.php',
    ),
    26 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_loocorreccion_veta_looMetaData.php',
    ),
    27 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_loo_veta_aplicacionMetaData.php',
    ),
    28 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_loo_casesMetaData.php',
    ),
    29 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_loo_activities_callsMetaData.php',
    ),
    30 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_loo_activities_meetingsMetaData.php',
    ),
    31 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_loo_activities_notesMetaData.php',
    ),
    32 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_loo_activities_tasksMetaData.php',
    ),
    33 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_loo_activities_emailsMetaData.php',
    ),
    34 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_liquidacion_opportunitiesMetaData.php',
    ),
    35 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_liquidacion_casesMetaData.php',
    ),
    36 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_liquidacion_activities_callsMetaData.php',
    ),
    37 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_liquidacion_activities_meetingsMetaData.php',
    ),
    38 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_liquidacion_activities_notesMetaData.php',
    ),
    39 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_liquidacion_activities_tasksMetaData.php',
    ),
    40 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_liquidacion_activities_emailsMetaData.php',
    ),
    41 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/veta_correccioncoe_veta_coeMetaData.php',
    ),
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Veta_PagoColegios',
      'to' => 'modules/Veta_PagoColegios',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Veta_Visa',
      'to' => 'modules/Veta_Visa',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Veta_Pagos',
      'to' => 'modules/Veta_Pagos',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Veta_NotificacionPagoColegio',
      'to' => 'modules/Veta_NotificacionPagoColegio',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Veta_Aplicacion',
      'to' => 'modules/Veta_Aplicacion',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Veta_ABNTaxFile',
      'to' => 'modules/Veta_ABNTaxFile',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Veta_COE',
      'to' => 'modules/Veta_COE',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Veta_LooCorreccion',
      'to' => 'modules/Veta_LooCorreccion',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Veta_Loo',
      'to' => 'modules/Veta_Loo',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Veta_Liquidacion',
      'to' => 'modules/Veta_Liquidacion',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Veta_CorreccionCOE',
      'to' => 'modules/Veta_CorreccionCOE',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_PagoColegios.php',
      'to_module' => 'Veta_PagoColegios',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_PagoColegios.php',
      'to_module' => 'Veta_PagoColegios',
      'language' => 'es_ES',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'en_us',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'es_ES',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'es_ES',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_PagoColegios.php',
      'to_module' => 'Veta_PagoColegios',
      'language' => 'en_us',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_PagoColegios.php',
      'to_module' => 'Veta_PagoColegios',
      'language' => 'es_ES',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Calls.php',
      'to_module' => 'Calls',
      'language' => 'en_us',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Calls.php',
      'to_module' => 'Calls',
      'language' => 'es_ES',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_PagoColegios.php',
      'to_module' => 'Veta_PagoColegios',
      'language' => 'en_us',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_PagoColegios.php',
      'to_module' => 'Veta_PagoColegios',
      'language' => 'es_ES',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'en_us',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'es_ES',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_PagoColegios.php',
      'to_module' => 'Veta_PagoColegios',
      'language' => 'en_us',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_PagoColegios.php',
      'to_module' => 'Veta_PagoColegios',
      'language' => 'es_ES',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'en_us',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'es_ES',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_PagoColegios.php',
      'to_module' => 'Veta_PagoColegios',
      'language' => 'en_us',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_PagoColegios.php',
      'to_module' => 'Veta_PagoColegios',
      'language' => 'es_ES',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Tasks.php',
      'to_module' => 'Tasks',
      'language' => 'en_us',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Tasks.php',
      'to_module' => 'Tasks',
      'language' => 'es_ES',
    ),
    22 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_PagoColegios.php',
      'to_module' => 'Veta_PagoColegios',
      'language' => 'en_us',
    ),
    23 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_PagoColegios.php',
      'to_module' => 'Veta_PagoColegios',
      'language' => 'es_ES',
    ),
    24 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Emails.php',
      'to_module' => 'Emails',
      'language' => 'en_us',
    ),
    25 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Emails.php',
      'to_module' => 'Emails',
      'language' => 'es_ES',
    ),
    26 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Visa.php',
      'to_module' => 'Veta_Visa',
      'language' => 'en_us',
    ),
    27 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Visa.php',
      'to_module' => 'Veta_Visa',
      'language' => 'es_ES',
    ),
    28 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_COE.php',
      'to_module' => 'Veta_COE',
      'language' => 'en_us',
    ),
    29 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_COE.php',
      'to_module' => 'Veta_COE',
      'language' => 'es_ES',
    ),
    30 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Visa.php',
      'to_module' => 'Veta_Visa',
      'language' => 'en_us',
    ),
    31 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Visa.php',
      'to_module' => 'Veta_Visa',
      'language' => 'es_ES',
    ),
    32 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'en_us',
    ),
    33 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'es_ES',
    ),
    34 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Cases.php',
      'to_module' => 'Cases',
      'language' => 'en_us',
    ),
    35 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Cases.php',
      'to_module' => 'Cases',
      'language' => 'es_ES',
    ),
    36 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Visa.php',
      'to_module' => 'Veta_Visa',
      'language' => 'en_us',
    ),
    37 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Visa.php',
      'to_module' => 'Veta_Visa',
      'language' => 'es_ES',
    ),
    38 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Pagos.php',
      'to_module' => 'Veta_Pagos',
      'language' => 'en_us',
    ),
    39 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Pagos.php',
      'to_module' => 'Veta_Pagos',
      'language' => 'es_ES',
    ),
    40 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Liquidacion.php',
      'to_module' => 'Veta_Liquidacion',
      'language' => 'en_us',
    ),
    41 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Liquidacion.php',
      'to_module' => 'Veta_Liquidacion',
      'language' => 'es_ES',
    ),
    42 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_NotificacionPagoColegio.php',
      'to_module' => 'Veta_NotificacionPagoColegio',
      'language' => 'en_us',
    ),
    43 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_NotificacionPagoColegio.php',
      'to_module' => 'Veta_NotificacionPagoColegio',
      'language' => 'es_ES',
    ),
    44 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_PagoColegios.php',
      'to_module' => 'Veta_PagoColegios',
      'language' => 'en_us',
    ),
    45 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_PagoColegios.php',
      'to_module' => 'Veta_PagoColegios',
      'language' => 'es_ES',
    ),
    46 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Aplicacion.php',
      'to_module' => 'Veta_Aplicacion',
      'language' => 'en_us',
    ),
    47 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Aplicacion.php',
      'to_module' => 'Veta_Aplicacion',
      'language' => 'es_ES',
    ),
    48 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'en_us',
    ),
    49 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'es_ES',
    ),
    50 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Cases.php',
      'to_module' => 'Cases',
      'language' => 'en_us',
    ),
    51 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Cases.php',
      'to_module' => 'Cases',
      'language' => 'es_ES',
    ),
    52 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Aplicacion.php',
      'to_module' => 'Veta_Aplicacion',
      'language' => 'en_us',
    ),
    53 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Aplicacion.php',
      'to_module' => 'Veta_Aplicacion',
      'language' => 'es_ES',
    ),
    54 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    55 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'es_ES',
    ),
    56 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Aplicacion.php',
      'to_module' => 'Veta_Aplicacion',
      'language' => 'en_us',
    ),
    57 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Aplicacion.php',
      'to_module' => 'Veta_Aplicacion',
      'language' => 'es_ES',
    ),
    58 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Calls.php',
      'to_module' => 'Calls',
      'language' => 'en_us',
    ),
    59 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Calls.php',
      'to_module' => 'Calls',
      'language' => 'es_ES',
    ),
    60 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Aplicacion.php',
      'to_module' => 'Veta_Aplicacion',
      'language' => 'en_us',
    ),
    61 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Aplicacion.php',
      'to_module' => 'Veta_Aplicacion',
      'language' => 'es_ES',
    ),
    62 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'en_us',
    ),
    63 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'es_ES',
    ),
    64 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Aplicacion.php',
      'to_module' => 'Veta_Aplicacion',
      'language' => 'en_us',
    ),
    65 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Aplicacion.php',
      'to_module' => 'Veta_Aplicacion',
      'language' => 'es_ES',
    ),
    66 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'en_us',
    ),
    67 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'es_ES',
    ),
    68 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Aplicacion.php',
      'to_module' => 'Veta_Aplicacion',
      'language' => 'en_us',
    ),
    69 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Aplicacion.php',
      'to_module' => 'Veta_Aplicacion',
      'language' => 'es_ES',
    ),
    70 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Tasks.php',
      'to_module' => 'Tasks',
      'language' => 'en_us',
    ),
    71 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Tasks.php',
      'to_module' => 'Tasks',
      'language' => 'es_ES',
    ),
    72 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Aplicacion.php',
      'to_module' => 'Veta_Aplicacion',
      'language' => 'en_us',
    ),
    73 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Aplicacion.php',
      'to_module' => 'Veta_Aplicacion',
      'language' => 'es_ES',
    ),
    74 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Emails.php',
      'to_module' => 'Emails',
      'language' => 'en_us',
    ),
    75 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Emails.php',
      'to_module' => 'Emails',
      'language' => 'es_ES',
    ),
    76 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_COE.php',
      'to_module' => 'Veta_COE',
      'language' => 'en_us',
    ),
    77 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_COE.php',
      'to_module' => 'Veta_COE',
      'language' => 'es_ES',
    ),
    78 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Aplicacion.php',
      'to_module' => 'Veta_Aplicacion',
      'language' => 'en_us',
    ),
    79 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Aplicacion.php',
      'to_module' => 'Veta_Aplicacion',
      'language' => 'es_ES',
    ),
    80 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_COE.php',
      'to_module' => 'Veta_COE',
      'language' => 'en_us',
    ),
    81 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_COE.php',
      'to_module' => 'Veta_COE',
      'language' => 'es_ES',
    ),
    82 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'en_us',
    ),
    83 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'es_ES',
    ),
    84 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Cases.php',
      'to_module' => 'Cases',
      'language' => 'en_us',
    ),
    85 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Cases.php',
      'to_module' => 'Cases',
      'language' => 'es_ES',
    ),
    86 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_COE.php',
      'to_module' => 'Veta_COE',
      'language' => 'en_us',
    ),
    87 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_COE.php',
      'to_module' => 'Veta_COE',
      'language' => 'es_ES',
    ),
    88 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    89 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'es_ES',
    ),
    90 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_COE.php',
      'to_module' => 'Veta_COE',
      'language' => 'en_us',
    ),
    91 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_COE.php',
      'to_module' => 'Veta_COE',
      'language' => 'es_ES',
    ),
    92 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Calls.php',
      'to_module' => 'Calls',
      'language' => 'en_us',
    ),
    93 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Calls.php',
      'to_module' => 'Calls',
      'language' => 'es_ES',
    ),
    94 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_COE.php',
      'to_module' => 'Veta_COE',
      'language' => 'en_us',
    ),
    95 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_COE.php',
      'to_module' => 'Veta_COE',
      'language' => 'es_ES',
    ),
    96 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'en_us',
    ),
    97 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'es_ES',
    ),
    98 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_COE.php',
      'to_module' => 'Veta_COE',
      'language' => 'en_us',
    ),
    99 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_COE.php',
      'to_module' => 'Veta_COE',
      'language' => 'es_ES',
    ),
    100 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'en_us',
    ),
    101 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'es_ES',
    ),
    102 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_COE.php',
      'to_module' => 'Veta_COE',
      'language' => 'en_us',
    ),
    103 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_COE.php',
      'to_module' => 'Veta_COE',
      'language' => 'es_ES',
    ),
    104 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Tasks.php',
      'to_module' => 'Tasks',
      'language' => 'en_us',
    ),
    105 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Tasks.php',
      'to_module' => 'Tasks',
      'language' => 'es_ES',
    ),
    106 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_COE.php',
      'to_module' => 'Veta_COE',
      'language' => 'en_us',
    ),
    107 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_COE.php',
      'to_module' => 'Veta_COE',
      'language' => 'es_ES',
    ),
    108 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Emails.php',
      'to_module' => 'Emails',
      'language' => 'en_us',
    ),
    109 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Emails.php',
      'to_module' => 'Emails',
      'language' => 'es_ES',
    ),
    110 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_LooCorreccion.php',
      'to_module' => 'Veta_LooCorreccion',
      'language' => 'en_us',
    ),
    111 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_LooCorreccion.php',
      'to_module' => 'Veta_LooCorreccion',
      'language' => 'es_ES',
    ),
    112 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Loo.php',
      'to_module' => 'Veta_Loo',
      'language' => 'en_us',
    ),
    113 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Loo.php',
      'to_module' => 'Veta_Loo',
      'language' => 'es_ES',
    ),
    114 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Loo.php',
      'to_module' => 'Veta_Loo',
      'language' => 'en_us',
    ),
    115 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Loo.php',
      'to_module' => 'Veta_Loo',
      'language' => 'es_ES',
    ),
    116 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Aplicacion.php',
      'to_module' => 'Veta_Aplicacion',
      'language' => 'en_us',
    ),
    117 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Aplicacion.php',
      'to_module' => 'Veta_Aplicacion',
      'language' => 'es_ES',
    ),
    118 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Cases.php',
      'to_module' => 'Cases',
      'language' => 'en_us',
    ),
    119 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Cases.php',
      'to_module' => 'Cases',
      'language' => 'es_ES',
    ),
    120 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Loo.php',
      'to_module' => 'Veta_Loo',
      'language' => 'en_us',
    ),
    121 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Loo.php',
      'to_module' => 'Veta_Loo',
      'language' => 'es_ES',
    ),
    122 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    123 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'es_ES',
    ),
    124 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Loo.php',
      'to_module' => 'Veta_Loo',
      'language' => 'en_us',
    ),
    125 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Loo.php',
      'to_module' => 'Veta_Loo',
      'language' => 'es_ES',
    ),
    126 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Calls.php',
      'to_module' => 'Calls',
      'language' => 'en_us',
    ),
    127 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Calls.php',
      'to_module' => 'Calls',
      'language' => 'es_ES',
    ),
    128 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Loo.php',
      'to_module' => 'Veta_Loo',
      'language' => 'en_us',
    ),
    129 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Loo.php',
      'to_module' => 'Veta_Loo',
      'language' => 'es_ES',
    ),
    130 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'en_us',
    ),
    131 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'es_ES',
    ),
    132 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Loo.php',
      'to_module' => 'Veta_Loo',
      'language' => 'en_us',
    ),
    133 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Loo.php',
      'to_module' => 'Veta_Loo',
      'language' => 'es_ES',
    ),
    134 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'en_us',
    ),
    135 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'es_ES',
    ),
    136 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Loo.php',
      'to_module' => 'Veta_Loo',
      'language' => 'en_us',
    ),
    137 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Loo.php',
      'to_module' => 'Veta_Loo',
      'language' => 'es_ES',
    ),
    138 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Tasks.php',
      'to_module' => 'Tasks',
      'language' => 'en_us',
    ),
    139 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Tasks.php',
      'to_module' => 'Tasks',
      'language' => 'es_ES',
    ),
    140 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Loo.php',
      'to_module' => 'Veta_Loo',
      'language' => 'en_us',
    ),
    141 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Loo.php',
      'to_module' => 'Veta_Loo',
      'language' => 'es_ES',
    ),
    142 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Emails.php',
      'to_module' => 'Emails',
      'language' => 'en_us',
    ),
    143 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Emails.php',
      'to_module' => 'Emails',
      'language' => 'es_ES',
    ),
    144 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Liquidacion.php',
      'to_module' => 'Veta_Liquidacion',
      'language' => 'en_us',
    ),
    145 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Liquidacion.php',
      'to_module' => 'Veta_Liquidacion',
      'language' => 'es_ES',
    ),
    146 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'en_us',
    ),
    147 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'es_ES',
    ),
    148 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Cases.php',
      'to_module' => 'Cases',
      'language' => 'en_us',
    ),
    149 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Cases.php',
      'to_module' => 'Cases',
      'language' => 'es_ES',
    ),
    150 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Liquidacion.php',
      'to_module' => 'Veta_Liquidacion',
      'language' => 'en_us',
    ),
    151 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Liquidacion.php',
      'to_module' => 'Veta_Liquidacion',
      'language' => 'es_ES',
    ),
    152 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    153 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'es_ES',
    ),
    154 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Liquidacion.php',
      'to_module' => 'Veta_Liquidacion',
      'language' => 'en_us',
    ),
    155 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Liquidacion.php',
      'to_module' => 'Veta_Liquidacion',
      'language' => 'es_ES',
    ),
    156 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Calls.php',
      'to_module' => 'Calls',
      'language' => 'en_us',
    ),
    157 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Calls.php',
      'to_module' => 'Calls',
      'language' => 'es_ES',
    ),
    158 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Liquidacion.php',
      'to_module' => 'Veta_Liquidacion',
      'language' => 'en_us',
    ),
    159 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Liquidacion.php',
      'to_module' => 'Veta_Liquidacion',
      'language' => 'es_ES',
    ),
    160 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'en_us',
    ),
    161 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'es_ES',
    ),
    162 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Liquidacion.php',
      'to_module' => 'Veta_Liquidacion',
      'language' => 'en_us',
    ),
    163 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Liquidacion.php',
      'to_module' => 'Veta_Liquidacion',
      'language' => 'es_ES',
    ),
    164 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'en_us',
    ),
    165 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'es_ES',
    ),
    166 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Liquidacion.php',
      'to_module' => 'Veta_Liquidacion',
      'language' => 'en_us',
    ),
    167 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Liquidacion.php',
      'to_module' => 'Veta_Liquidacion',
      'language' => 'es_ES',
    ),
    168 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Tasks.php',
      'to_module' => 'Tasks',
      'language' => 'en_us',
    ),
    169 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Tasks.php',
      'to_module' => 'Tasks',
      'language' => 'es_ES',
    ),
    170 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Liquidacion.php',
      'to_module' => 'Veta_Liquidacion',
      'language' => 'en_us',
    ),
    171 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Liquidacion.php',
      'to_module' => 'Veta_Liquidacion',
      'language' => 'es_ES',
    ),
    172 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Emails.php',
      'to_module' => 'Emails',
      'language' => 'en_us',
    ),
    173 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Emails.php',
      'to_module' => 'Emails',
      'language' => 'es_ES',
    ),
    174 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_CorreccionCOE.php',
      'to_module' => 'Veta_CorreccionCOE',
      'language' => 'en_us',
    ),
    175 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_CorreccionCOE.php',
      'to_module' => 'Veta_CorreccionCOE',
      'language' => 'es_ES',
    ),
    176 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_COE.php',
      'to_module' => 'Veta_COE',
      'language' => 'en_us',
    ),
    177 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_COE.php',
      'to_module' => 'Veta_COE',
      'language' => 'es_ES',
    ),
    178 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/es_ES.lang.php',
      'to_module' => 'application',
      'language' => 'es_ES',
    ),
    179 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),
  'vardefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_pagocolegios_opportunities_Veta_PagoColegios.php',
      'to_module' => 'Veta_PagoColegios',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_pagocolegios_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_pagocolegios_activities_calls_Calls.php',
      'to_module' => 'Calls',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_pagocolegios_activities_calls_Veta_PagoColegios.php',
      'to_module' => 'Veta_PagoColegios',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_pagocolegios_activities_meetings_Meetings.php',
      'to_module' => 'Meetings',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_pagocolegios_activities_meetings_Veta_PagoColegios.php',
      'to_module' => 'Veta_PagoColegios',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_pagocolegios_activities_notes_Notes.php',
      'to_module' => 'Notes',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_pagocolegios_activities_notes_Veta_PagoColegios.php',
      'to_module' => 'Veta_PagoColegios',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_pagocolegios_activities_tasks_Tasks.php',
      'to_module' => 'Tasks',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_pagocolegios_activities_tasks_Veta_PagoColegios.php',
      'to_module' => 'Veta_PagoColegios',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_pagocolegios_activities_emails_Emails.php',
      'to_module' => 'Emails',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_pagocolegios_activities_emails_Veta_PagoColegios.php',
      'to_module' => 'Veta_PagoColegios',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_visa_veta_coe_Veta_Visa.php',
      'to_module' => 'Veta_Visa',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_visa_veta_coe_Veta_COE.php',
      'to_module' => 'Veta_COE',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_visa_opportunities_Veta_Visa.php',
      'to_module' => 'Veta_Visa',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_visa_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_visa_cases_Cases.php',
      'to_module' => 'Cases',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_visa_cases_Veta_Visa.php',
      'to_module' => 'Veta_Visa',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_pagos_veta_liquidacion_Veta_Pagos.php',
      'to_module' => 'Veta_Pagos',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_pagos_veta_liquidacion_Veta_Liquidacion.php',
      'to_module' => 'Veta_Liquidacion',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_notificacionpagocolegio_veta_pagocolegios_Veta_NotificacionPagoColegio.php',
      'to_module' => 'Veta_NotificacionPagoColegio',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_notificacionpagocolegio_veta_pagocolegios_Veta_PagoColegios.php',
      'to_module' => 'Veta_PagoColegios',
    ),
    22 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_aplicacion_opportunities_Veta_Aplicacion.php',
      'to_module' => 'Veta_Aplicacion',
    ),
    23 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_aplicacion_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
    24 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_aplicacion_cases_Cases.php',
      'to_module' => 'Cases',
    ),
    25 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_aplicacion_cases_Veta_Aplicacion.php',
      'to_module' => 'Veta_Aplicacion',
    ),
    26 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_aplicacion_activities_calls_Calls.php',
      'to_module' => 'Calls',
    ),
    27 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_aplicacion_activities_calls_Veta_Aplicacion.php',
      'to_module' => 'Veta_Aplicacion',
    ),
    28 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_aplicacion_activities_meetings_Meetings.php',
      'to_module' => 'Meetings',
    ),
    29 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_aplicacion_activities_meetings_Veta_Aplicacion.php',
      'to_module' => 'Veta_Aplicacion',
    ),
    30 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_aplicacion_activities_notes_Notes.php',
      'to_module' => 'Notes',
    ),
    31 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_aplicacion_activities_notes_Veta_Aplicacion.php',
      'to_module' => 'Veta_Aplicacion',
    ),
    32 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_aplicacion_activities_tasks_Tasks.php',
      'to_module' => 'Tasks',
    ),
    33 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_aplicacion_activities_tasks_Veta_Aplicacion.php',
      'to_module' => 'Veta_Aplicacion',
    ),
    34 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_aplicacion_activities_emails_Emails.php',
      'to_module' => 'Emails',
    ),
    35 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_aplicacion_activities_emails_Veta_Aplicacion.php',
      'to_module' => 'Veta_Aplicacion',
    ),
    36 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_coe_veta_aplicacion_Veta_COE.php',
      'to_module' => 'Veta_COE',
    ),
    37 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_coe_veta_aplicacion_Veta_Aplicacion.php',
      'to_module' => 'Veta_Aplicacion',
    ),
    38 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_coe_opportunities_Veta_COE.php',
      'to_module' => 'Veta_COE',
    ),
    39 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_coe_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
    40 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_coe_cases_Cases.php',
      'to_module' => 'Cases',
    ),
    41 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_coe_cases_Veta_COE.php',
      'to_module' => 'Veta_COE',
    ),
    42 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_coe_activities_calls_Calls.php',
      'to_module' => 'Calls',
    ),
    43 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_coe_activities_calls_Veta_COE.php',
      'to_module' => 'Veta_COE',
    ),
    44 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_coe_activities_meetings_Meetings.php',
      'to_module' => 'Meetings',
    ),
    45 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_coe_activities_meetings_Veta_COE.php',
      'to_module' => 'Veta_COE',
    ),
    46 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_coe_activities_notes_Notes.php',
      'to_module' => 'Notes',
    ),
    47 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_coe_activities_notes_Veta_COE.php',
      'to_module' => 'Veta_COE',
    ),
    48 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_coe_activities_tasks_Tasks.php',
      'to_module' => 'Tasks',
    ),
    49 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_coe_activities_tasks_Veta_COE.php',
      'to_module' => 'Veta_COE',
    ),
    50 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_coe_activities_emails_Emails.php',
      'to_module' => 'Emails',
    ),
    51 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_coe_activities_emails_Veta_COE.php',
      'to_module' => 'Veta_COE',
    ),
    52 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_loocorreccion_veta_loo_Veta_LooCorreccion.php',
      'to_module' => 'Veta_LooCorreccion',
    ),
    53 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_loocorreccion_veta_loo_Veta_Loo.php',
      'to_module' => 'Veta_Loo',
    ),
    54 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_loo_veta_aplicacion_Veta_Loo.php',
      'to_module' => 'Veta_Loo',
    ),
    55 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_loo_veta_aplicacion_Veta_Aplicacion.php',
      'to_module' => 'Veta_Aplicacion',
    ),
    56 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_loo_cases_Cases.php',
      'to_module' => 'Cases',
    ),
    57 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_loo_cases_Veta_Loo.php',
      'to_module' => 'Veta_Loo',
    ),
    58 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_loo_activities_calls_Calls.php',
      'to_module' => 'Calls',
    ),
    59 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_loo_activities_calls_Veta_Loo.php',
      'to_module' => 'Veta_Loo',
    ),
    60 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_loo_activities_meetings_Meetings.php',
      'to_module' => 'Meetings',
    ),
    61 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_loo_activities_meetings_Veta_Loo.php',
      'to_module' => 'Veta_Loo',
    ),
    62 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_loo_activities_notes_Notes.php',
      'to_module' => 'Notes',
    ),
    63 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_loo_activities_notes_Veta_Loo.php',
      'to_module' => 'Veta_Loo',
    ),
    64 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_loo_activities_tasks_Tasks.php',
      'to_module' => 'Tasks',
    ),
    65 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_loo_activities_tasks_Veta_Loo.php',
      'to_module' => 'Veta_Loo',
    ),
    66 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_loo_activities_emails_Emails.php',
      'to_module' => 'Emails',
    ),
    67 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_loo_activities_emails_Veta_Loo.php',
      'to_module' => 'Veta_Loo',
    ),
    68 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_liquidacion_opportunities_Veta_Liquidacion.php',
      'to_module' => 'Veta_Liquidacion',
    ),
    69 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_liquidacion_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
    70 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_liquidacion_cases_Cases.php',
      'to_module' => 'Cases',
    ),
    71 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_liquidacion_cases_Veta_Liquidacion.php',
      'to_module' => 'Veta_Liquidacion',
    ),
    72 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_liquidacion_activities_calls_Calls.php',
      'to_module' => 'Calls',
    ),
    73 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_liquidacion_activities_calls_Veta_Liquidacion.php',
      'to_module' => 'Veta_Liquidacion',
    ),
    74 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_liquidacion_activities_meetings_Meetings.php',
      'to_module' => 'Meetings',
    ),
    75 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_liquidacion_activities_meetings_Veta_Liquidacion.php',
      'to_module' => 'Veta_Liquidacion',
    ),
    76 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_liquidacion_activities_notes_Notes.php',
      'to_module' => 'Notes',
    ),
    77 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_liquidacion_activities_notes_Veta_Liquidacion.php',
      'to_module' => 'Veta_Liquidacion',
    ),
    78 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_liquidacion_activities_tasks_Tasks.php',
      'to_module' => 'Tasks',
    ),
    79 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_liquidacion_activities_tasks_Veta_Liquidacion.php',
      'to_module' => 'Veta_Liquidacion',
    ),
    80 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_liquidacion_activities_emails_Emails.php',
      'to_module' => 'Emails',
    ),
    81 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_liquidacion_activities_emails_Veta_Liquidacion.php',
      'to_module' => 'Veta_Liquidacion',
    ),
    82 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_correccioncoe_veta_coe_Veta_CorreccionCOE.php',
      'to_module' => 'Veta_CorreccionCOE',
    ),
    83 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/veta_correccioncoe_veta_coe_Veta_COE.php',
      'to_module' => 'Veta_COE',
    ),
  ),
  'layoutfields' => 
  array (
    0 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    1 => 
    array (
      'additional_fields' => 
      array (
        'Calls' => 'veta_pagocolegios_activities_calls_name',
      ),
    ),
    2 => 
    array (
      'additional_fields' => 
      array (
        'Meetings' => 'veta_pagocolegios_activities_meetings_name',
      ),
    ),
    3 => 
    array (
      'additional_fields' => 
      array (
        'Notes' => 'veta_pagocolegios_activities_notes_name',
      ),
    ),
    4 => 
    array (
      'additional_fields' => 
      array (
        'Tasks' => 'veta_pagocolegios_activities_tasks_name',
      ),
    ),
    5 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    6 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    7 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    8 => 
    array (
      'additional_fields' => 
      array (
        'Cases' => 'veta_visa_cases_name',
      ),
    ),
    9 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    10 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    11 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    12 => 
    array (
      'additional_fields' => 
      array (
        'Cases' => 'veta_aplicacion_cases_name',
      ),
    ),
    13 => 
    array (
      'additional_fields' => 
      array (
        'Calls' => 'veta_aplicacion_activities_calls_name',
      ),
    ),
    14 => 
    array (
      'additional_fields' => 
      array (
        'Meetings' => 'veta_aplicacion_activities_meetings_name',
      ),
    ),
    15 => 
    array (
      'additional_fields' => 
      array (
        'Notes' => 'veta_aplicacion_activities_notes_name',
      ),
    ),
    16 => 
    array (
      'additional_fields' => 
      array (
        'Tasks' => 'veta_aplicacion_activities_tasks_name',
      ),
    ),
    17 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    18 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    19 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    20 => 
    array (
      'additional_fields' => 
      array (
        'Cases' => 'veta_coe_cases_name',
      ),
    ),
    21 => 
    array (
      'additional_fields' => 
      array (
        'Calls' => 'veta_coe_activities_calls_name',
      ),
    ),
    22 => 
    array (
      'additional_fields' => 
      array (
        'Meetings' => 'veta_coe_activities_meetings_name',
      ),
    ),
    23 => 
    array (
      'additional_fields' => 
      array (
        'Notes' => 'veta_coe_activities_notes_name',
      ),
    ),
    24 => 
    array (
      'additional_fields' => 
      array (
        'Tasks' => 'veta_coe_activities_tasks_name',
      ),
    ),
    25 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    26 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    27 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    28 => 
    array (
      'additional_fields' => 
      array (
        'Cases' => 'veta_loo_cases_name',
      ),
    ),
    29 => 
    array (
      'additional_fields' => 
      array (
        'Calls' => 'veta_loo_activities_calls_name',
      ),
    ),
    30 => 
    array (
      'additional_fields' => 
      array (
        'Meetings' => 'veta_loo_activities_meetings_name',
      ),
    ),
    31 => 
    array (
      'additional_fields' => 
      array (
        'Notes' => 'veta_loo_activities_notes_name',
      ),
    ),
    32 => 
    array (
      'additional_fields' => 
      array (
        'Tasks' => 'veta_loo_activities_tasks_name',
      ),
    ),
    33 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    34 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    35 => 
    array (
      'additional_fields' => 
      array (
        'Cases' => 'veta_liquidacion_cases_name',
      ),
    ),
    36 => 
    array (
      'additional_fields' => 
      array (
        'Calls' => 'veta_liquidacion_activities_calls_name',
      ),
    ),
    37 => 
    array (
      'additional_fields' => 
      array (
        'Meetings' => 'veta_liquidacion_activities_meetings_name',
      ),
    ),
    38 => 
    array (
      'additional_fields' => 
      array (
        'Notes' => 'veta_liquidacion_activities_notes_name',
      ),
    ),
    39 => 
    array (
      'additional_fields' => 
      array (
        'Tasks' => 'veta_liquidacion_activities_tasks_name',
      ),
    ),
    40 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    41 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
  ),
);