<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */
$relationships = array (
  'veta_requerimiento_modified_user' => 
  array (
    'id' => '59b74645-7139-23e5-a95d-61084ad80a68',
    'relationship_name' => 'veta_requerimiento_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Veta_Requerimiento',
    'rhs_table' => 'veta_requerimiento',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'veta_requerimiento_created_by' => 
  array (
    'id' => '5a48c290-e552-986c-49e3-61084a146a12',
    'relationship_name' => 'veta_requerimiento_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Veta_Requerimiento',
    'rhs_table' => 'veta_requerimiento',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'veta_requerimiento_assigned_user' => 
  array (
    'id' => '5aaa1bde-67d3-1131-aeae-61084a532c20',
    'relationship_name' => 'veta_requerimiento_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Veta_Requerimiento',
    'rhs_table' => 'veta_requerimiento',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'securitygroups_veta_requerimiento' => 
  array (
    'id' => '5ae344c8-4acc-063a-49cc-61084a919833',
    'relationship_name' => 'securitygroups_veta_requerimiento',
    'lhs_module' => 'SecurityGroups',
    'lhs_table' => 'securitygroups',
    'lhs_key' => 'id',
    'rhs_module' => 'Veta_Requerimiento',
    'rhs_table' => 'veta_requerimiento',
    'rhs_key' => 'id',
    'join_table' => 'securitygroups_records',
    'join_key_lhs' => 'securitygroup_id',
    'join_key_rhs' => 'record_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'module',
    'relationship_role_column_value' => 'Veta_Requerimiento',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'veta_requerimiento_activities_1_emails' => 
  array (
    'id' => '92e45066-dc6d-76e8-4586-61084a306d31',
    'relationship_name' => 'veta_requerimiento_activities_1_emails',
    'lhs_module' => 'Veta_Requerimiento',
    'lhs_table' => 'veta_requerimiento',
    'lhs_key' => 'id',
    'rhs_module' => 'Emails',
    'rhs_table' => 'emails',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Veta_Requerimiento',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'veta_requerimiento_leads' => 
  array (
    'id' => '93c9be2d-13d6-63bb-b869-61084aa9a4e7',
    'relationship_name' => 'veta_requerimiento_leads',
    'lhs_module' => 'Leads',
    'lhs_table' => 'leads',
    'lhs_key' => 'id',
    'rhs_module' => 'Veta_Requerimiento',
    'rhs_table' => 'veta_requerimiento',
    'rhs_key' => 'id',
    'join_table' => 'veta_requerimiento_leads_c',
    'join_key_lhs' => 'veta_requerimiento_leadsleads_ida',
    'join_key_rhs' => 'veta_requerimiento_leadsveta_requerimiento_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'veta_requerimiento_activities_1_meetings' => 
  array (
    'id' => '959e96d6-5659-515f-46f3-61084a2e4171',
    'relationship_name' => 'veta_requerimiento_activities_1_meetings',
    'lhs_module' => 'Veta_Requerimiento',
    'lhs_table' => 'veta_requerimiento',
    'lhs_key' => 'id',
    'rhs_module' => 'Meetings',
    'rhs_table' => 'meetings',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Veta_Requerimiento',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'veta_requerimiento_contacts' => 
  array (
    'id' => '97825ecc-8a3f-573c-7c9c-61084aa28c56',
    'relationship_name' => 'veta_requerimiento_contacts',
    'lhs_module' => 'Contacts',
    'lhs_table' => 'contacts',
    'lhs_key' => 'id',
    'rhs_module' => 'Veta_Requerimiento',
    'rhs_table' => 'veta_requerimiento',
    'rhs_key' => 'id',
    'join_table' => 'veta_requerimiento_contacts_c',
    'join_key_lhs' => 'veta_requerimiento_contactscontacts_ida',
    'join_key_rhs' => 'veta_requerimiento_contactsveta_requerimiento_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'veta_requerimiento_activities_1_notes' => 
  array (
    'id' => '98e491c7-96e6-9302-c36b-61084ad34011',
    'relationship_name' => 'veta_requerimiento_activities_1_notes',
    'lhs_module' => 'Veta_Requerimiento',
    'lhs_table' => 'veta_requerimiento',
    'lhs_key' => 'id',
    'rhs_module' => 'Notes',
    'rhs_table' => 'notes',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Veta_Requerimiento',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'veta_requerimiento_activities_1_tasks' => 
  array (
    'id' => '9c53cd5b-1f33-2051-4f9d-61084a74feca',
    'relationship_name' => 'veta_requerimiento_activities_1_tasks',
    'lhs_module' => 'Veta_Requerimiento',
    'lhs_table' => 'veta_requerimiento',
    'lhs_key' => 'id',
    'rhs_module' => 'Tasks',
    'rhs_table' => 'tasks',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Veta_Requerimiento',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'veta_requerimiento_veta_recibo' => 
  array (
    'id' => '9ccae3e5-7617-8941-f51e-61084acddc14',
    'relationship_name' => 'veta_requerimiento_veta_recibo',
    'lhs_module' => 'Veta_Requerimiento',
    'lhs_table' => 'veta_requerimiento',
    'lhs_key' => 'id',
    'rhs_module' => 'Veta_Recibo',
    'rhs_table' => 'veta_recibo',
    'rhs_key' => 'id',
    'join_table' => 'veta_requerimiento_veta_recibo_c',
    'join_key_lhs' => 'veta_requerimiento_veta_reciboveta_requerimiento_ida',
    'join_key_rhs' => 'veta_requerimiento_veta_reciboveta_recibo_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'veta_requerimiento_activities_1_calls' => 
  array (
    'id' => '9f732026-ebd3-a8e1-e492-61084aceb7d3',
    'relationship_name' => 'veta_requerimiento_activities_1_calls',
    'lhs_module' => 'Veta_Requerimiento',
    'lhs_table' => 'veta_requerimiento',
    'lhs_key' => 'id',
    'rhs_module' => 'Calls',
    'rhs_table' => 'calls',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Veta_Requerimiento',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'veta_requerimiento_veta_presupuesto' => 
  array (
    'id' => 'a3a6054c-9806-548a-691b-61084a2dd102',
    'relationship_name' => 'veta_requerimiento_veta_presupuesto',
    'lhs_module' => 'Veta_Requerimiento',
    'lhs_table' => 'veta_requerimiento',
    'lhs_key' => 'id',
    'rhs_module' => 'Veta_Presupuesto',
    'rhs_table' => 'veta_presupuesto',
    'rhs_key' => 'id',
    'join_table' => 'veta_requerimiento_veta_presupuesto_c',
    'join_key_lhs' => 'veta_requerimiento_veta_presupuestoveta_requerimiento_ida',
    'join_key_rhs' => 'veta_requerimiento_veta_presupuestoveta_presupuesto_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'veta_requerimiento_cases_1' => 
  array (
    'rhs_label' => 'Casos',
    'lhs_label' => 'Requerimiento',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'Veta_Requerimiento',
    'rhs_module' => 'Cases',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'veta_requerimiento_cases_1',
  ),
);