<?php

require_once( 'modules/Veta_Recibo/Veta_Recibo.php' );
require_once( 'include/MVC/View/views/view.edit.php' );
require_once( 'modules/Veta_Presupuesto/Veta_Presupuesto.php' );

class Veta_ReciboViewRecibo extends ViewEdit
{
    function __construct() {
        parent::__construct();
    }

    function preDisplay() {

        $r = new Veta_Recibo();
        $p = new Veta_Presupuesto();
        $p->retrieve( $_REQUEST[ 'pid' ] );

        if( $r->is_gerente_contable() ) {

            $recibos = $p->get_linked_beans( 'veta_recibo_veta_presupuesto' , 'Veta_Recibo' );

            if( count( $recibos ) == 0 ) {
                if( isset( $p->id ) and ! empty( $p->id ) ) {
                    $r = new Veta_Recibo();
                    $r = $r->new_recibo( $p );

                    header( "Location: index.php?module=Veta_Recibo&action=DetailView&record=" . $r->id );
                    exit;
                }

                parent::preDisplay(); // TODO: Change the autogenerated stub
            }
            else {
                $p->redireccionar( 'No se puede crear un recibo por que ya existe uno' , $p->id );
            }
        }
        else {
            $p->redireccionar( 'Solo un usuario con rol gerente contable puede crear un recibo' , $p->id );
        }


    }

    function display() {

        echo "No fue posible crear el recibo";
    }
}